### ISSUE TITLE
Plotly.js angular 6 wrapper

### ISSUE THREAD

**Issue by AbdolrezaMadi** [plotly/angular-plotly.js#10]
Hi,

Is there any official angular 6 wrapper for plotly.js?
If not at the moment, do you have it in your roadmap, and when will it be released?

Thanks,

**Comment by andrefarzat** [comment]
Hi, @AbdolrezaMadi, this lib works on angular 6.
What issues you're having?

**Comment by AbdolrezaMadi** [comment]
Hi @andrefarzat 
Thanks for your feedback. I couldn't find any information neither on plotly website nor on git about supported angular versions. 
I have not faced any issue, since currently I'm just comparing plotly vs highchart. We are using angular 6 framework with highchart, but there are very interesting charts (e.g. line chart) from plotly that we would like to use as well (assuming they will work in angular 6).
So, to be specific the line charts have been tested on angular 6?
Thanks,

**Comment by andrefarzat** [comment]
@AbdolrezaMadi `angular-plotly.js` is a wrapper for the [plotly.js itself](https://plot.ly/javascript/). Therefore, everything that works on plotlyjs will work. This wrapper is tested from angular 4.x and on, and intended to give the angular peculiarities such as a component to display the graph ( `<plotly-plot />` ), the observers to update the graph once the given data is changed, etc etc 

As an example, I copied a [linear graph from plotly's website](https://plot.ly/javascript/line-charts/#line-and-scatter-plot) and reproduced on angular 6.

### Print
<img width="1680" alt="screen shot 2018-07-26 at 6 12 42 pm" src="https://user-images.githubusercontent.com/649219/43288900-b420d9d6-90ff-11e8-94b2-a0dbdecf506c.png">

### Code ( app.component.ts )
```ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'agora';

  public graph = {
    data: [
      { x: [1, 2, 3, 4], y: [10, 15, 13, 17], mode: 'markers' },
      { x: [2, 3, 4, 5], y: [16, 5, 11, 9], mode: 'lines' },
      { x: [1, 2, 3, 4], y: [12, 9, 15, 12], mode: 'lines+markers' }
    ],
    layout: { title: 'Line and Scatter Plot' }
  };
}
```

Please, check the [README.md](https://github.com/plotly/angular-plotly.js#readme) to see how to install it. If you have more questions, please re-open the issue 😸
