### ISSUE TITLE
Fluid example doesn't shrink vertically

### ISSUE THREAD

**Issue by Helveg** [plotly/angular-plotly.js#102]
Using 

```
  <plotly-plot [data]="graph.data" [layout]="graph.layout" [config]="{resize: true}"
     [useResizeHandler]="true" [style]="{position: 'relative', width: '100%', height: '100%'}">
  </plotly-plot>
```

Doesn't shrink the plot vertically. When you refresh the page in a smaller window you can increase the vertical size but then again not shrink it

**Comment by andrefarzat** [comment]
Hello @Helveg , I could not replicate your issue. May I ask you to use the `vertical-issue` (https://github.com/plotly/angular-plotly.js/tree/vertical-issue) branch and edit the `responsiveness` component (https://github.com/plotly/angular-plotly.js/tree/vertical-issue/src/app/demo/responsiveness) and commit the code with the issue ?
Thank you 😸

**Comment by Helveg** [comment]
I will put it on my to-do list ;)
