### ISSUE TITLE
Installation problem with Angular 9

### ISSUE THREAD

**Issue by rissom** [plotly/angular-plotly.js#107]
Hi,

the quickstart guide does not work for me. The browser console says:

main.ts:12 Error: Invalid PlotlyJS object. Please check https://github.com/plotly/angular-plotly.js#quick-start to see how to add PlotlyJS to your project.
    at new PlotlyModule (angular-plotly.js.js:482)
    at Object.PlotlyModule_Factory [as factory] (angular-plotly.js.js:492)
    at R3Injector.hydrate (core.js:16865)
    at R3Injector.get (core.js:16617)
    at core.js:16662
    at Set.forEach (<anonymous>)
    at R3Injector._resolveInjectorDefTypes (core.js:16658)
    at new NgModuleRef$1 (core.js:36011)
    at NgModuleFactory$1.create (core.js:36110)
    at core.js:42293    

I use:

Angular CLI: 9.1.0
Node: 10.16.3
OS: win32 x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.1.0
@ngtools/webpack                  9.0.7
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

Any ideas?
Cheers,

Thorsten

**Comment by andrefarzat** [comment]
Hello, @rissom. As the error message says, the PlotlyJS object is invalid. Which version of `plotly.js` you're using? 
If you haven't installed it, you may consider using `PlotlyViaCDNModule` (https://github.com/plotly/angular-plotly.js#plotly-via-cdn-module ) as it downloads automatically via plotly's official cdn

**Comment by acmeplus** [comment]
I confirm using the CDNModule works fine. Regular npm install didn't work, however testing the same version (1.53.0) via CDN works fine.

**Comment by CKitisak** [comment]
hi @andrefarzat ,

Do you have any idea why do I got this error in the debug console:
```
plotly.js:24965 Uncaught TypeError: Cannot read property 'document' of undefined
    at plotly.js:24965
    at Object.165 (plotly.js:34511)
    at o (plotly.js:7)
    at plotly.js:7
    at Object.717.../constants/numerical (plotly.js:106510)
    at o (plotly.js:7)
    at plotly.js:7
    at Object.1.../src/lib (plotly.js:10)
    at o (plotly.js:7)
    at plotly.js:7
```

my shared module file:
```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import * as PlotlyJS from 'plotly.js/dist/plotly.js';
import { PlotlyModule } from 'angular-plotly.js';
PlotlyModule.plotlyjs = PlotlyJS;

@NgModule({
  imports: [CommonModule, PlotlyModule],
  exports: [CommonModule, PlotlyModule]
})
export class SharedModule { }
```

FYI: It works fine when using `Plotly Via Window Module` but not the method above.

My packages:
@angular/core": "~9.1.1",
"angular-plotly.js": "^2.0.0",
"plotly.js": "^1.53.0",

**Comment by andrefarzat** [comment]
Hello @CKitisak , this issue is with `plotly.js` itself. Please, refere to the `plotly.js` issues for it: (eg.: https://github.com/plotly/plotly.js/issues/3518 )
I dunno about angular universal, but I don't know if `plotly.js` is designed to run on the server side
