### ISSUE TITLE
this is undefined error

### ISSUE THREAD

**Issue by manuelpastor** [plotly/angular-plotly.js#111]
Hi!

The demo works fine for me (locally and as CDN module). When I integrates the library in my project using PlotlyViaCDNModule it works fine as well.

However, when I install it locally it fails this the following error. Any help will be most welcomed!

TypeError: this is undefinedplotly.js:24965
    ./node_modules/plotly.js/dist/plotly.js/</<[165]</< plotly.js:24965
    ./node_modules/plotly.js/dist/plotly.js/</<[165]< plotly.js:34511
    o plotly.js:7
    o plotly.js:7
    ./node_modules/plotly.js/dist/plotly.js/</<[717]< plotly.js:106510
    o plotly.js:7
    o plotly.js:7
    ./node_modules/plotly.js/dist/plotly.js/</<[1]< plotly.js:10
    o plotly.js:7
    o plotly.js:7
    ./node_modules/plotly.js/dist/plotly.js/</<[695]< plotly.js:103268
    o plotly.js:7
    o plotly.js:7
    ./node_modules/plotly.js/dist/plotly.js/</<[14]< plotly.js:242
    o plotly.js:7
    o plotly.js:7
    ./node_modules/plotly.js/dist/plotly.js/</<[26]< plotly.js:398
    o plotly.js:7
    r plotly.js:7
    js plotly.js:7
    js plotly.js:7
    js plotly.js:7
    Webpack 12
        __webpack_require__
        ts
        __webpack_require__
        ts
        __webpack_require__
        0
        __webpack_require__
        checkDeferredModules
        webpackJsonpCallback
        <anonymous>
        InnerModuleEvaluation
        evaluation

My system configuration:

Angular CLI: 9.1.1
Node: 12.16.1
OS: win32 x64

Angular: 9.1.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.0-next.0
@angular-devkit/build-angular     0.1000.0-next.0
@angular-devkit/build-optimizer   0.1000.0-next.0
@angular-devkit/build-webpack     0.1000.0-next.0
@angular-devkit/core              10.0.0-next.0
@angular-devkit/schematics        9.1.1
@angular/cdk                      9.2.1
@angular/cli                      9.1.1
@angular/material                 9.2.1
@ngtools/webpack                  10.0.0-next.0
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.1

**Comment by manuelpastor** [comment]
OK! I noted that this has been already reported, sorry!

**Comment by leogout** [comment]
Hello, can you give a link to the issue please ? I have this bug and can't find the related issue.
