### ISSUE TITLE
Update data in Angular 9

### ISSUE THREAD

**Issue by lesianocmn** [plotly/angular-plotly.js#114]
Hello,

I'm trying to update the data you see in the chart but it doesn't doing nothing. Don't know if it's a issue or I'm doing it wrong, but because I didn't find any solution I writing it here. Sorry if it's not the case.
My code:

```
HTML:
   <plotly-plot [data]="graph.data" [layout]="graph.layout" [config]="graph.config"
                     (plotly_click)="chartClick($event)"
                     [updateOnDataChange]="true"
                     [updateOnLayoutChange]="true"
                     [updateOnlyWithRevision]="true"
                     [revision]="revision"
                     ></plotly-plot>

.ts:

datasetIndex:number;
revision:number;
  graph = {
    data: [{x:[1,2,3,4], y:[20,30,40,50], type:'scatter'}],
    layout: {   width: 600, height: 550, title: '', hovermode: 'closest', showlegend: false  },
    config: { displayModeBar: false, scrollZoom: false }
  }

chartClick(e) {
       this.datasetIndex = e.points[0].curveNumber;
}
updateChart(index,value){
this.graph.data[this.datasetIndex].x[index] = value;
 this.revision = +1;
}

```

The function updateChart is called in a textbox with the index that you want to change and the new value. 
I'm trying to update the chart without luck. 
Thanks.

**Comment by andrefarzat** [comment]
hello @lesianocmn , you said that the function `updateChart` is being called on a textbox. The `console.log` confirms it ?
Also, the line `this.revision = +1;` doesn't look correct. Should it be `this.revision += 1;`?

**Comment by lesianocmn** [comment]
Hello @andrefarzat , thanks for the reply. Yes, debugging it, I see that the `this.graph.data[this.datasetIndex].x[index]` is updated with new value. 
sorry my mistake. I put the revision working now, but still not updating the chart.

**Comment by lesianocmn** [comment]
Hi @andrefarzat . I could make it work. Looks like you can't update only one value and then he updates the chart, you should update all the data. Doing this:

```
   let data = this.graph.data[this.datasetIndex].x.slice();
    data[index] = value;
    this.graph.data[this.datasetIndex].x = data;
```

It updates the chart as I wanted. Thanks for your help.
