### ISSUE TITLE
Plotly error on double click outside selected zone - Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by apurv2** [plotly/angular-plotly.js#116]
Environment:
Plotly via CDN Module - Angular. I have the following code in app.module.ts
```
PlotlyViaCDNModule.plotlyVersion = 'latest'; 
PlotlyViaCDNModule.plotlyBundle = 'basic'; 
```
Steps to recreate:
1. Select any part of the map using the select tool.
2. Click outside the selected area

Expected behavior : 
Deselect the selected area.

Actual Behaviour :
throws this error:

core.js:6210 ERROR TypeError: Cannot read property 'slice' of undefined
    at H (plotly-latest.min.js:61)
    at q (plotly-latest.min.js:61)
    at plotly-latest.min.js:61
    at Object.r.call (plotly-latest.min.js:61)
    at Ut (plotly-latest.min.js:61)
    at Object.Lt [as clickFn] (plotly-latest.min.js:61)
    at HTMLDocument.T (plotly-latest.min.js:61)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41762)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)

**Comment by andrefarzat** [comment]
hello @apurv2 , is it possible to you provide the `layout` and `data` objects you're using ?

**Comment by apurv2** [comment]
here is the data array:
```
[
	{
		"type": "bar",
		"y": [
			57,
			527,
			1,
			674,
			506,
			5,
			2,
			14,
			14,
			358,
			1
		],
		"x": [
			"aa",
			"bb",
			"cc",
			"dd",
			"ee",
			"ff",
			"gg",
			"hh",
			"ii",
			"jj",
			"dd"			
		]
	}
]
```

here is the layout array 

`{"showlegend":false}
`

**Comment by apurv2** [comment]
html:
 ```
<plotly-plot  [data]="data"
                    [useResizeHandler]="true" [style]="{ width: '100%', height: '500%'}" [layout]=layout>
                </plotly-plot>
```

and the component.ts file
```
        this.data = [
          {
            "type": "bar",
            "y": [
              57,
              527,
              1,
              674,
              506,
              5,
              2,
              14,
              14,
              358,
              1
            ],
            "x": [
              "aa",
              "bb",
              "cc",
              "dd",
              "ee",
              "ff",
              "gg",
              "hh",
              "ii",
              "jj",
              "dd"
            ]
          }
        ];
        this.layout = { showlegend: false };
```

**Comment by jwang01** [comment]
I also got similar errror when click on `Autoscale` button when I have two plots bound to the same range :
plotly-basic.js?d8ae:43786 Uncaught TypeError: Cannot read property 'slice' of undefined at axRangeSupplyDefaultsByPass

**Comment by jwang01** [comment]
![image](https://user-images.githubusercontent.com/43763385/85757448-54286480-b6c4-11ea-95d4-f18121722a4e.png)

**Comment by jebenois** [comment]
Having the same issue as @jwang01 . It happens when clicking on autoscale after messing a bit with the chart.
