### ISSUE TITLE
Documentation references React

### ISSUE THREAD

**Issue by lundmikkel** [plotly/angular-plotly.js#117]
> **Warning:** for the time being, this component may _mutate_ its `layout` and `data` props in response to user input, going against **React** rules

[https://github.com/plotly/angular-plotly.js#basic-props](https://github.com/plotly/angular-plotly.js#basic-props)

**Comment by andrefarzat** [comment]
@lundmikkel was an outdated quote. Thanks for pointed it out. Just removed 😸
