### ISSUE TITLE
plotly_click fires twice when plot is updated

### ISSUE THREAD

**Issue by robert-hirsch-po** [plotly/angular-plotly.js#122]
`plotly_click` event fires twice, once when clicked, and once when the chart is updated. I'm using the `updateOnlyWithRevision` set to `true`. The event will fire twice regardless of the `updateOnlyWithRevision` flag set to `true`.

**Comment by andrefarzat** [comment]
@robert-hirsch-po this is an odd behaviour. Will create a demo page to try to simulate it

**Comment by robert-hirsch-po** [comment]
Issue was a bug on my part. Some bad data which created duplicate lines on a 3dScatter plot. Both lines were firing click events.

**Comment by andrefarzat** [comment]
@robert-hirsch-po thanks for letting us know. I could not replicate the issue here after trying several different approaches
