### ISSUE TITLE
Suport for IE11

### ISSUE THREAD

**Issue by aarontoys** [plotly/angular-plotly.js#123]
Does angular-plotly.js work in IE11?

I'm trying to get the the demo "Quick Start" chart to display in IE11 without success. All other browsers I tested seem to be working 100%.

I'm currently using:

Angular: 9.1
plotly.js-basic-dist: 1.54.7
angular-plotly.js: 2.0

Errors in IE11:
"Error while plotting: SyntaxError"
"Error: Uncaught (in promise): TypeError: Unable to get property 'data' of undefined or null reference"

The promise returned by `this.plotly.newPlot(...)` seems to be rejected, but I've checked that `this.data` being passed into that function is as per the example. 

I've also notice some strange behavior with the class names having extra spaces between the characters:

![Screen Shot 2020-08-10 at 4 37 32 PM](https://user-images.githubusercontent.com/15148578/89838192-dd3a1480-db27-11ea-8f3d-a640bd22ea9f.png)

Any help on this issue would be greatly appreciated.

**Comment by andrefarzat** [comment]
hello @aarontoys. We haven't tried the demo on the IE11. This also can be the way angular built the javascript. Have you tried setting the target to es5 ? (reference: https://angular.io/guide/deployment#differential-builds)

**Comment by aarontoys** [comment]
@andrefarzat thanks for getting back to me so quickly. Unfortunately, the `target` property in our `tsconfig.json` was already set to `es5`. Any other thoughts or ideas? Maybe you guys could see if you're able to get it to work in IE 11?
