### ISSUE TITLE
The documented plotly.js import path breaks VS Code.

### ISSUE THREAD

**Issue by TrevorKarjanis** [plotly/angular-plotly.js#125]
The [documentation](https://github.com/plotly/angular-plotly.js#quick-start) imports plotly.js with the path ```'plotly.js/dist/plotly.js'```. With this path, VS Code's Go to Definition command goes to the imported symbol at the top of the file. With the path ```'plotly.js'```, it goes to the type in ```@types/plotly.js``` correctly. Is it necessary to use the documented path, or can ```'plotly.js'``` be used so that type definitions can be accessed?

version 2.0.0

**Comment by andrefarzat** [comment]
Hello @TrevorKarjanis, we aren't using `@types/plotly.js` inside `angular-plotly.js` for it was causing issues with the final bundle when released. Thus, we are not aware of this behaviour in the VS code.
To help us understand, please tell us the use case you need to use `plotly.js` directly instead of using or `<plotly-plot>` component or `PlotlyService` 😺

**Comment by TrevorKarjanis** [comment]
I apologize if this issue was more appropriate for plotly/plotly.js, but the path was documented in this repository. We are actually using the types from @types/plotly.js like PlotData, Layout, Template, and Config as strict types that are passed into the PlotComponent. To clarify, we are using the plotly.js types directly, not the API.

**Comment by andrefarzat** [comment]
I see. Well, we could not add the types in our lib, for supporting multiple versions of `plotly.js` has proven to be a nightmare.  Please, [check here](https://github.com/plotly/angular-plotly.js/blob/v2.0.0/src/app/shared/plotly.service.ts#L57) that the method `PlotlyService.getPlotly` isn't typed (i.e.: type `any`) to avoid the issues with multiple versions. 

maybe you could force type the return of the function? Something like:
```typescript
const plotly: Plotly = this.plotlyService.getPlotly();
```
?

**Comment by TrevorKarjanis** [comment]
Yes, that's exactly what I want to do. My question is why ```'plotly.js/dist/plotly.js'``` is used in the documentation rather than ```'plotly.js'``` and if there is any issue with using the latter. If not, I will use ```'plotly.js'```, so that VS Code will work with plotly types. It looks like ```'plotly.js'``` points to ```'plotly.js/lib/index.js'``` which appears to be the un-concatenated version. It seems to work, so I might continue with that, and we can close this issue!

**Comment by andrefarzat** [comment]
We recommend using `plotly.js/dist/plotly.js`for the issue with the final bundle size ( please, check [this comment](https://github.com/plotly/angular-plotly.js/issues/50#issuecomment-473682668)).

You can continue with that if it suits you 😸 

Thank you for your patience in explaining it. Will close the isse. Feel free to reopen if necessary
