### ISSUE TITLE
Update documentation and changelog to mention plotlyVersion is now private

### ISSUE THREAD

**Issue by Lectem** [plotly/angular-plotly.js#129]
It seems 44acbfd5fb8a6645b9ad5307fcb89d9b5076925b changed `PlotlyViaCDNModule.plotlyVersion` to be private, but this is not mentioned in the documentation nor the changelog.

`PlotlyViaCDNModule.plotlyVersion = '1.47.4';` becomes `PlotlyViaCDNModule.setPlotlyVersion('1.47.4');`

**Comment by andrefarzat** [comment]
@Lectem you were right! Thanks a lot for letting us know 😸
