### ISSUE TITLE
ERROR: rgba is not a function

### ISSUE THREAD

**Issue by jordanpowell88** [plotly/angular-plotly.js#131]
I'm getting the following error when I try to import Plotly into my module.

core.js:4197 ERROR Error: Uncaught (in promise): TypeError: rgba is not a function
TypeError: rgba is not a function

It's throwing from `gl_format_color.js` on line 19:
var colorDfltRgba = rgba(colorDflt);

I'm using Angular version 10

Any ideas why this is happening? It completely stops my module from loading using lazy loading.

     import { PlotlyModule } from 'angular-plotly.js';
     import * as PlotlyJS from 'plotly.js';
     PlotlyModule.plotlyjs = PlotlyJS;
 
     imports: [
       PlotlyModule
     ]

**Comment by afarzat-ed** [comment]
Hello @jordanpowell88. You just updated to angular 10 (from 9?) and got this error?
Angular compiler/bundler does a lot of stuff to optimize the code, it *might* be this.

I have two suggestions:
* Exchange te `plotly.js` to `plotly.js-dist`. Check it out: https://www.npmjs.com/package/plotly.js-dist
* Or: Try up the `PlotlyViaCDNModule` to confirm the issue only in the `PlotlyModule` module (and with the compiler)

**Comment by jordanpowell88** [comment]
Thanks for the feedback. Using `PlotlyViaCDNModule` did the trick.
