### ISSUE TITLE
 Cannot read property 'document' of undefined

### ISSUE THREAD

**Issue by Amrelmalky** [plotly/angular-plotly.js#132]
<img width="960" alt="BOM html" src="https://user-images.githubusercontent.com/69693889/94698829-fa29e180-0339-11eb-87f3-4c0f5b14505b.png">
<img width="960" alt="script " src="https://user-images.githubusercontent.com/69693889/94698906-0b72ee00-033a-11eb-80b8-428296611fad.png">
![move](https://user-images.githubusercontent.com/69693889/94698927-10d03880-033a-11eb-88ed-8b340eb1abda.jpg)
![change bkg](https://user-images.githubusercontent.com/69693889/94698946-13cb2900-033a-11eb-8929-de28bfd20ac5.jpg)

**Comment by afarzat-ed** [comment]
Hello @Amrelmalky 
I can't see how the prints are related to `angular-plotly.js`

**Comment by Amrelmalky** [comment]
![change bkg](https://user-images.githubusercontent.com/69693889/94699076-39583280-033a-11eb-9056-73877fb93e44.jpg)
![move](https://user-images.githubusercontent
![change bkg](https://user-images.githubusercontent.com/69693889/94706484-8809ca80-0342-11eb-80e8-0444e27883df.jpg)
![move](https://user-images.githubusercontent.com/69693889/94706501-8e984200-0342-11eb-8501-5e2cdf632dae.jpg)

.com/69693889/94699113-4412c780-033a-11eb-94cb-549832c0feb6.jpg)

**Comment by owfilip** [comment]
Hi!
Any updates on that issue? It throws the error even after adding chrome 86 to .browserslistrc

**Comment by andrefarzat** [comment]
hello @owfilip , the `document` issue is related to `plotly.js` itself and how angular's compile transpiles it. 
Have you tried using [`PlotlyViaCDNModule` module](https://github.com/plotly/angular-plotly.js#plotly-via-cdn-module) ?

sources:
[1] https://github.com/plotly/angular-plotly.js/issues/89
[2] https://github.com/plotly/angular-plotly.js/issues/75

**Comment by owfilip** [comment]
Thanks! Works!
However, there is one more step, obviously one has to get `angular-ploltly.js`. Worth adding to readme [Plotly Via CDN Module](https://github.com/plotly/angular-plotly.js#plotly-via-cdn-module):
`npm i --save angular-plotly.js`
