### ISSUE TITLE
Disable animations in Sunburst

### ISSUE THREAD

**Issue by tanvi-cota** [plotly/angular-plotly.js#134]
Issue -
I am trying to disable the animation of sunbust using angular-plotly(v1.8.0)
`onSunburstClick(e: { points: any; event: MouseEvent }) {
      return false;
  }`
But this seems, not to work and the SunBurst still animates to the selected slice

We can achieve the same via JS, eg -
https://codepen.io/etpinard/pen/GRKNyNO

**Comment by andrefarzat** [comment]
Hello, @tanvi-cota 

how you passed the function/event to plotly?
Have you tried this : https://github.com/plotly/angular-plotly.js/issues/52#issuecomment-476018478 ?

**Comment by tanvi-cota** [comment]
@andrefarzat  This works! thanks for pointing this out. But I support Schmaga comments, that it should be something where we can list of the disable events or animation (in this case)

**Comment by andrefarzat** [comment]
@tanvi-cota this is a seldon request ( you're the second one ). But I would be glad do implement something if we can come up with a good api / schema to make it work consistently 😺 

Gonna close this issue, but feel free to reopen or create another one with a suggestion
