### ISSUE TITLE
Possible to add [updateOnConfigChange]?

### ISSUE THREAD

**Issue by icoker** [plotly/angular-plotly.js#138]
I have plots inside of resizable divs, and I would like the 'export plot to image' functionality to be able to export the image as the size of component on screen. I already have the nativeElement size of the plot, and I can modify the config (toImageButtonOptions) during a resize event, but plotly does not update the mode bar when the configuration is changed.

**Comment by andrefarzat** [comment]
Hello, @icoker . A bit hard to understand what is the issue. The modebar isn't updated when you change the config object? As in you'd like to have the export button only with a certain size of the graph?

**Comment by icoker** [comment]
@andrefarzat Correct, ideally the modebar would be updated when the config object is modified. This way, when I change specified size in the toImageButtonOptions property via a resize event, the button on the modebar would export at the new size.

**Comment by icoker** [comment]
Apologies @andrefarzat , I believe this issue can be closed. It seems like, when modifying the entire object, the modebar did not update, but modifying each individual property in the toImageButtonOptions object does seem to cause to modebar to update.

**Comment by andrefarzat** [comment]
@icoker oh, I see. That's why the angular's diffChecker isn't working. As alternative, you could use revision property: https://github.com/plotly/angular-plotly.js#basic-props
