### ISSUE TITLE
[request] ng-universal compatibility

### ISSUE THREAD

**Issue by alanpurple** [plotly/angular-plotly.js#140]
plotlly.js/lib/dom.js cause errors because it use "document.getElementById"

It should be handled such as using Injected Document from @angular/common

**Comment by andrefarzat** [comment]
@alanpurple we can't support ng-universal once plotly.js itself doesn't render on the server side 😿

**Comment by alanpurple** [comment]
@andrefarzat I see, so this is about plotly.js itself ..... thx
