### ISSUE TITLE
Expose relayout method to either service or component

### ISSUE THREAD

**Issue by Mesya82** [plotly/angular-plotly.js#141]
plotly.js has a very neat method called `relayout` which, basically, allows devs to alter plotly's `layout` properties partially and update the plot much faster. I'd like `angular-plotly` to expose this method either in service or in component (preferably).

**Comment by andrefarzat** [comment]
Hello, @Mesya82 . You can access the whole `Plotly` object using the `PlotlyService` like so: https://github.com/plotly/angular-plotly.js/blob/master/FAQ.md#how-to-access-global-plotly-object-code 😸
