### ISSUE TITLE
Request: Props for before/after modebar buttons that change axes

### ISSUE THREAD

**Issue by andrew-matteson** [plotly/angular-plotly.js#145]
I'm interested in stashing the axes information before these events fire. I have an app in which hovering over 1 plot changes what's drawn in another. Some users want to click the autoscale button, hover over the plot that triggers changes, then restore the plot to the original axes by setting 'reset'.

The only way I see to do this is to get before/after emitters for the axis information when autoscale, reset, pan, or zoom is clicked in the modebar.

If there is an approach that would work without this feature, could you point me towards it?

Thanks so much!

**Comment by andrefarzat** [comment]
Hello, @andrew-matteson , it's hard to understand. First looking at [plotlyjs events docs](https://plotly.com/javascript/plotlyjs-events/), I couldn't find event handlers for autoscale, reset, pan, or zoom is clicked in the modebar. 
Maybe we can use a differ(e.g.: [IterableDiffer](https://angular.io/api/core/IterableDiffer) or [KeyValueDiffer](https://angular.io/api/core/KeyValueDiffer)) on [ngDoCheck](https://angular.io/api/core/DoCheck) to know when to trigger these events?
