### ISSUE TITLE
Angular 11 support

### ISSUE THREAD

**Issue by moaxey** [plotly/angular-plotly.js#154]
I guess this not trivial moving from @angular-devkit/build-ng-packagr to ng-packagr. Is anybody working on it?

**Comment by andrefarzat** [comment]
Hello @moaxey , at the beginning the library were published using `ng-packagr`, but since version 3.x and angular 10.x (I think) we are following the angular guide to library: https://angular.io/guide/creating-libraries

Is there a specific use case you need the `ng-packagr` ?

**Comment by thomaschampagne** [comment]
+1 for Angular 11 support 👍  😃  !

```
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^10.0.9" from angular-plotly.js@3.0.0
npm ERR! node_modules/angular-plotly.js
npm ERR!   angular-plotly.js@"^3.0.0" from the root project
```
