### ISSUE TITLE
How to use Plotly.extendTraces in wrapper <plotly-plot></plotly-plot>

### ISSUE THREAD

**Issue by Prateek-Havanur** [plotly/angular-plotly.js#16]
i am trying to achieve Plotly.extendTraces method. i have installed plotly/angular-plotly.js and trying to plot use extendtraces method

**Comment by andrefarzat** [comment]
Hi @Prateek-Havanur , sorry being late in replying here. 
In the version `0.1.5` you are able to use `const Plotly = PlotlyService.getPlotly()` to get the plotly.js object, thus you're able to run `Plotly.extendTrace('div-id', {})`. Please, see [this comment](https://github.com/plotly/angular-plotly.js/issues/14#issuecomment-423710255) for more details. The documentation for this method is coming.

I am closing this issue, but feel free to reopen it if the doubt continues 😸
