### ISSUE TITLE
Error: Can't resolve 'path' or 'fs' in 'node_modules/plotly.js/node_modules/image-size/lib'.

### ISSUE THREAD

**Issue by intotecho** [plotly/angular-plotly.js#164]
I had some issues getting this working with Angular 12.0.1,  Node: 16.2.0, npm 7.13.0

The npm packages

├── ng2-charts@2.4.2

├── plotly.js@1.58.4

Leads to compile errors: 

```bash
./node_modules/plotly.js/node_modules/image-size/lib/index.js:3:9-22 - Error: Module not found: Error: Can't resolve 'fs' in '/home/ user/project/node_modules/plotly.js/node_modules/image-size/lib'

./node_modules/plotly.js/node_modules/image-size/lib/index.js:5:11-26 - Error: Module not found: Error: Can't resolve 'path' in '/home/user/project/node_modules/plotly.js/node_modules/image-size/lib'
```
I fixed these by patching the node models files that call fs and path

```
sed -i 's/require("path")/require("something-i-know-exists")/g' node_modules/some-package/file-error-is-in.js
sed -i 's/require("fs")/require("something-i-know-exists")/g' node_modules/some-package/file-error-is-in.js
```

Patching node  modules is not great practice but I couldn't find a work around.
There seems to be a PR for plotly.js  https://github.com/plotly/plotly.js/pull/5388/files That addresses the issue.

Angular 7x won't allow fs or path. None of the other [suggestions ](https://github.com/angular/angular-cli/issues/10681) to ignore fs and path worked for me. 

P.S. I also added this to polyfills.ts which is unrelated to the above but needed before the plot would run.
https://stackoverflow.com/questions/52744489/uncaught-referenceerror-global-is-not-defined-while-using-plotly-in-angular-6

Any suggestions welcome

**Comment by andrefarzat** [comment]
Hello, @intotecho . Have you tried another module? Such as [PlotlyViaCDNModule](https://github.com/plotly/angular-plotly.js#plotly-via-cdn-module) ? This avoids to bundle the plotly.js lib inside the angular's code, thus these errors might no appear

**Comment by intotecho** [comment]
Hi @andrefarzat, Sorry I don't think that is an option for me as the app must work offline. But its a good suggestion for others who don't have this constraint.

**Comment by andrefarzat** [comment]
@intotecho well, there is the [PlotlyViaWindowModule](https://github.com/plotly/angular-plotly.js#plotly-via-window-module) as well, which avoids the bundle of plotly.js into the final code. Have you seen it?

**Comment by intotecho** [comment]
Yes, this seems to work fine. 

I had to remove the old references from the module i.e 
imports: { 
   // PlotlyModule, 
  PlotlyViaWindowModule,
]

I am using 
- @angular/cli@12.0.3
- @angular/core@12.0.3
-angular-plotly.js@4.0.0
-plotly.js@2.0.0
- stream@0.0.2

It also fixed an issued with WebGL not working.  https://github.com/plotly/angular-plotly.js/issues/165

Thankyou.

**Comment by p1-nbr** [comment]
I got this error because I was importing from the `plotly.js` instead of `plotly.js-dist-min`
