### ISSUE TITLE
Incompatible with Angular 12?

### ISSUE THREAD

**Issue by Carnageous** [plotly/angular-plotly.js#168]
It seems that angular-plotly-js is incompatible with Angular 12.

I got the following error when trying to update an existing project from Angular 11 to Angular 12:

```
Package "angular-plotly.js" has an incompatible peer dependency to "@angular/common" (requires "^10.0.9" (extended), would install "12.1.0").
Package "angular-plotly.js" has an incompatible peer dependency to "@angular/core" (requires "^10.0.9" (extended), would install "12.1.0").
```

Would it be possible to publish a version that can deal with Angular 12? I am not comfortable force-installing it.

**System information:**
- Angular: 11 (ng-updating to 12)
- Node: v16.3.0
- NPM: 7.15.1
- angular-plotly.js: ^3.0.0

**Comment by andrefarzat** [comment]
@Carnageous Which angular-plotly.js version you're using? 4.0.0 ?
I am asking it for in we are using ">10.0.9" as semver for angular to avoid these issues ( check : https://github.com/plotly/angular-plotly.js/blob/v4.0.0/projects/plotly/package.json )

**Comment by Carnageous** [comment]
Seems like you are right @andrefarzat! Apparently I was using some 3.x version. Sorry for the inconvenience.
