### ISSUE TITLE
Remove the node_modules step from the docs

### ISSUE THREAD

**Issue by andrefarzat** [plotly/angular-plotly.js#172]
Refers: https://github.com/plotly/angular-plotly.js/issues/57#issuecomment-897801164

**Comment by elgs** [comment]
I got the error without doing the rename:

```
Error: src/app/bazaar.module.ts:16:27 - error TS7016: 
Could not find a declaration file for module 'plotly.js-dist'. 
'/Users/qianchen/code/myapp/node_modules/plotly.js-dist/plotly.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/plotly.js-dist` 
  if it exists or add a new declaration (.d.ts) file containing `declare module 'plotly.js-dist';`
```

So should I install `@types/plotly.js-dist` as the error message suggested instead of installing @types/plotly.js as the doc suggested?

**Comment by andrefarzat** [comment]
is there a `@types/plotly.js-dist` ? if yes, it should solve it. Please, try it up and let us know 😺

**Comment by elgs** [comment]
@andrefarzat I just tried and found the package `@types/plotly.js-dist` doesn't exist. So what should I do with the error?

**Comment by andrefarzat** [comment]
@elgs As a quickfix, create a file called `index.d.ts` at the rood of the `src` folder and put this line:
```ts
declare module 'plotly.js-dist-min';
```

I will see if it's possible to add this declarations inside the project to avoid installing external types

**Comment by elgs** [comment]
Thanks @andrefarzat. I will keep using the cdn until this is fixed.

**Comment by andrefarzat** [comment]
I am trying to add types to the plotly package: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55120

**Comment by andrefarzat** [comment]
@elgs the `@types/plotly.js-dist-min` is live. With this, we can do: 
```sh
$ npm install angular-plotly.js plotly.js-dist-min --save
$ npm install @types/plotly.js-dist-min --save-dev
```

and things will work out ! 😸 
Please, update to `angular-plotly.js` 4.0.3 and test it

**Comment by elgs** [comment]
Thank you @andrefarzat, it works now! 🎉
