### ISSUE TITLE
Can't download static image programmatically

### ISSUE THREAD

**Issue by philkonick** [plotly/angular-plotly.js#173]
Hey there

I am trying to export my graph as an image, ultimately to send to an API to be added to a PDF file. 

I have tried [this solution](https://github.com/plotly/angular-plotly.js/issues/66#issuecomment-496560984) but keep getting the following error: `Property 'downloadImage' does not exist on type 'Promise<any>'`

I am running Angular 12.2.1 and angular-plotly.js 4.0.2, and am using the PlotlyViaCDNModule, although I have also tried a standard configuration.

My exact code is as follows:
`		<plotly-plot
			divId="reportGraph"
			*ngIf="chartReady"
			[data]="chartData"
			[config]="chartConfig"
		></plotly-plot>`
`	public downloadGraph(): void {
		const reportGraph = this.plotlyService.getInstanceByDivId('reportGraph');
		this.plotlyService.getPlotly().downloadImage(reportGraph, {
			format: 'png',
			width: 1024,
			height: 800,
			filename: 'test.png'
		});
	}`

I am getting the error on the "downloadImage" function.

Please help!

**Comment by andrefarzat** [comment]
Hello @philkonick. As the error says, `plotlyService.getPlotly()` returns a promise. You can see the code here: 
https://github.com/plotly/angular-plotly.js/blob/master/projects/plotly/src/lib/plotly.service.ts#L56

Thus, you should be using the `await` statement to get the plotly object from it.
A quick refactor on your code would be:

```ts
public async downloadGraph(): Promise<void> {
    const reportGraph = this.plotlyService.getInstanceByDivId('reportGraph');
    const plotly = await this.plotlyService.getPlotly();
    plotly.downloadImage(reportGraph, { format: 'png', width: 1024, height: 800, filename: 'test.png' });
}
```

**Comment by philkonick** [comment]
Amazing, works perfectly. Thanks so much for the assistance!
