### ISSUE TITLE
Plotly via Window Module path error

### ISSUE THREAD

**Issue by jml0123** [plotly/angular-plotly.js#176]
Hello, I have tried to use a global script to minimize by bundle size by by adding this line to my angular.json file according to the docs. However, the build process fails because in the latest release, the path doesn't exist in `node_modules`.

This throws an error during the build process:
```
   "scripts": [
              "node_modules/plotly.js/dist/plotly.min.js"
    ]
```
Error:
`An unhandled exception occurred: Script file node_modules/plotly.js/dist/plotly.min.js does not exist.`

I have followed the installation instructions and noticed that plotly.min.js is in a different folder, `/plotly.js-dist-min`.
The script works after changing the path to match the new file structure.

This works:
```
   "scripts": [
              "node_modules/plotly.js-dist-min/plotly.min.js"
    ]
```

_However_, after analyzing my bundle size with and without the script, it seems like the bundle is actually smaller _without_ the script! 

Bundle size using Plotly via  window module:
![G-Zipped app with global script](https://user-images.githubusercontent.com/29313716/135151752-d1e45ed0-fe9c-4955-a69c-8b75af9538b7.PNG)

Bundle size using Plotly via window module (~ 1mb smaller):
![G-Zipped app without global script](https://user-images.githubusercontent.com/29313716/135152109-8a9ea96c-d303-47bc-8028-ff4558fb1c1c.PNG)

Any idea as to why this is the case?

**Comment by andrefarzat** [comment]
Hello, @jml0123 . The difference is related to the file sizes.
I just did `npm install plotly.js plotly.js-dist-min` and did a `du -h` in each file you mentioned:

<img width="451" alt="Screen Shot 2021-09-28 at 17 37 39" src="https://user-images.githubusercontent.com/649219/135162060-31ded361-2200-4a10-9acf-7500bea54f89.png">
