### ISSUE TITLE
Custom buttons Zoom in & out from Angular App

### ISSUE THREAD

**Issue by Haamdiben** [plotly/angular-plotly.js#178]
Hello, I was looking for a way to hide the bar of plotly charts (done) and create my own button to zoom in & out, so as I was searching I've found already someone that was looking almost for the same thing https://github.com/plotly/angular-plotly.js/issues/14

so i've tried this part  :
 `Plotly.relayout( figure, {
‘xaxis.autorange’: true,
‘yaxis.autorange’: true
});`

but am facing problems because the plotly service can't knows this function. Here are packages that i'am using:

`    "plotly.js": "^2.3.1",
    "plotly.js-dist": "^2.3.0",
    "plotly.js-dist-min": "^2.5.1",
    "@types/plotly.js": "^1.54.13",
    "angular-plotly.js": "^4.0.4",`

So if anyone knows anything, it will be helpful, thank you all !

**Comment by Haamdiben** [comment]
@andrefarzat Hello and thank you for your quick answer, actually it's like the method relayout doesn't exist

Here is a printed screen of my code
![bug5](https://user-images.githubusercontent.com/38927706/136799414-daf35b0b-932a-4bb1-abe4-fd8480bfaea7.PNG)

**Comment by andrefarzat** [comment]
@Haamdiben you're missing the `await` keyword to unwrap the [promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise).
As you're using on `ngOnInit` (a non-async method), try this:
```ts
this.plotly.getPlotly().then(plotly => {
    const graph = this.plotly.getInstanceByDivId('graph');
    plotly.relayout(graph, ... );
});

**Comment by Haamdiben** [comment]
Yeah! You're right, that fixed the issue! Maybe I should learn a little more about the promises.
Thank you so much!
