### ISSUE TITLE
Prod mode label error

### ISSUE THREAD

**Issue by FlacosFlace** [plotly/angular-plotly.js#19]
When build to prod mode every time I hover line to show label like this: 
![vyber_078](https://user-images.githubusercontent.com/31759187/47082878-5e1b7400-d20f-11e8-82b0-544a9ad9c6de.png)

This error will show:
![vyber_079](https://user-images.githubusercontent.com/31759187/47082905-725f7100-d20f-11e8-81e6-1c0ad551f6b4.png)

Any idea why?

**Comment by FlacosFlace** [comment]
Thanks.

**Comment by EzraBrooks** [comment]
Still experiencing this error as of Angular 7.0.3. Angular team thinks they fixed it at angular/angular-cli#11129, but it's still not working in this particular scenario.

**Comment by jderuere** [comment]
Still not working with angular 7.1.0. Are we sure it comes from angular package?

**Comment by hpardess** [comment]
the error still exists in production mood. 
`node --max_old_space_size=12000 ./node_modules/.bin/ng build --prod --source-map`

`ERROR TypeError: Cannot read property 'call' of undefined
 at main.6890494d6e6277c18b3b.js:1 ...`
