### ISSUE TITLE
Plotly.js >= v2

### ISSUE THREAD

**Issue by mojoaxel** [plotly/angular-plotly.js#194]
It looks like plotly.js >= v2 is also supported by this component.

But I wanted to open this issue here to discuss switching to >= v2 also [internally](https://github.com/plotly/angular-plotly.js/blob/master/package.json#L22).

This would mean a major change, so maybe together with angular 13 support?

**Comment by andrefarzat** [comment]
@mojoaxel just updated! Thank you!
