### ISSUE TITLE
Unable to hide plotly mode bar 

### ISSUE THREAD

**Issue by fmonegaglia** [plotly/angular-plotly.js#200]
Hi,

I am unable to get rid of the plotly toolbar. My template is 

        <plotly-plot [data]="graph.data" [layout]="graph.layout" [config]="graph.config"></plotly-plot>

where graph.config is defined in the component body as

        graph.config = {
            responsive:true,
            displayModeBar:false,
        };

Everything else works, except the config argument seems to be ignored.

I am running Angular CLI 13.3.8 with
 - @types/plotly.js-dist-min@2.3.0
 - angular-plotly.js@4.0.4
 - plotly.js-dist-min@2.12.1

**Comment by andrefarzat** [comment]
Hello @fmonegaglia. I made a quick test here and it worked as expected for me. Here is the test: https://stackblitz.com/edit/angular-ivy-dkfcej?file=src/app/app.component.ts . I used angular 14 and PlotlyViaCDNModule, those are the only differences. 

Can I ask you to modify this stackblitz and replicate the issue?

**Comment by fmonegaglia** [comment]
There was something wrong with my angular-plotly installation. I removed it and reinstalled it and now it works!
Thanks
