### ISSUE TITLE
How to use in lazy loaded modules

### ISSUE THREAD

**Issue by thatsmeta** [plotly/angular-plotly.js#208]
I have an Angular 13 app with two lazy loaded modules which need to have plotly charts.
How would I go about integrating angular-plotly into my application using PlotlyViaWindowModule?
If I import it into the AppModule, the <plotly-plot> component is not available in the lazy loaded modules.

**Comment by ssalveMobiltex** [comment]
Hi @andrefarzat  
I did resolve this by creating a seperate shared  module. And then putting the Plotly code in the seperate module. And importing the module in my lazy loaded module. 

eg. 
Step 1. Create a shared-plotly.module.ts
Code:
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { PlotlyViaWindowModule } from 'angular-plotly.js';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    PlotlyViaWindowModule
  ],
  exports: [
    CommonModule,
    PlotlyViaWindowModule
  ]
})

Step 2: Import the shared module in your lazy loaded module
