### ISSUE TITLE
updatePlot() recreates plot

### ISSUE THREAD

**Issue by elliot-osborne** [plotly/angular-plotly.js#22]
When updating a plot's data, [updatePlot()](https://github.com/plotly/angular-plotly.js/blob/master/src/app/plotly/plot/plot.component.ts#L206) calls createPlot() which uses plotly.newPlot(). Would it be possible to use [Plotly.react](https://plot.ly/javascript/plotlyjs-function-reference/#plotlyreact) or [Plotly.update](https://plot.ly/javascript/plotlyjs-function-reference/#plotlyupdate) here instead?

**Comment by arlowhite** [comment]
In the past I found that switching between using `Plotly.react` and the other functions didn't work or had various bugs. I don't know if Plotly is designed for using both APIs at the same time. So at some point I decided to switch to exclusively using `Plotly.react`

If you're interested in a `Plotly.react` based approach, I created:
https://github.com/arlowhite/angular-plotly-react

**Comment by andrefarzat** [comment]
Please, update to version `0.2.2` which supports angular 7.x and uses `plotlyjs.react` method as you suggested 😸
