### ISSUE TITLE
event firing multiple times unnecessarily

### ISSUE THREAD

**Issue by skidvd** [plotly/angular-plotly.js#226]
I am noticing that at the time of chart creation/initialization various events, including (afterPlot) and (relayout), are being invoke multiple times (7 or more times each) without any changes to plot configuration nor data.  Why are these being triggered so often?  I had assumed that each would be triggered only once, but that does not appear to be the case?  FYI, this happens even when I am using [updateOnlyWithRevision] = "true"

**Comment by andrefarzat** [comment]
@skidvd this is plotly.js itself triggering the events. 
`[updateOnlyWithRevision] = "true"` only avoids the `ngDoCheck` to force the update (see: https://github.com/plotly/angular-plotly.js/blob/master/projects/plotly/src/lib/plotly.component.ts#L159)

What do you think should be the behaviour in this case? We can't change plotly.js , but we can think in (1) correct the `[updateOnlyWithRevision]` behaviour or (2) create another attribute/parameter to make any of these events to trigger

**Comment by skidvd** [comment]
I am looking for a single event that allows me to know when the chart is fully 'settled'.  Meaning that the chart is both fully rendered and available to respond to all user interactions with it.  As it stands, I am not sure how many of the (afterPlot) and (relayout) events to expect or which one is the 'final' one that signifies that the chart has 'settled'?

Perhaps a new settled event can be created for this purpose?

**Comment by andrefarzat** [comment]
Seeing the documentation for `AfterPlot event`, what we want might be the syntax with the promise (e.g.: `Plotly.newPlot('myDiv', data, layout, config).then(postPlotHandler);` which *might* triggers only once.

Have you tested it? I will test it today and, if it triggers only once as I expect, it might be it 😸
