### ISSUE TITLE
Angular Plotly not working with angular universal

### ISSUE THREAD

**Issue by tarunmishra592** [plotly/angular-plotly.js#229]
Hi,

I am using angular plotly and facing issue while adding plotly with window.

`Error: Plotly object not found on window.`

<img width="793" alt="Screenshot 2023-03-21 at 3 04 30 PM" src="https://user-images.githubusercontent.com/9740620/226589979-c480ac13-55de-4245-a4cd-07d9603c5d58.png">

i already added this in angular.json
`"scripts": ["./node_modules/plotly.js/dist/plotly.min.js"]`

**app.module.ts**
```
import { CommonModule } from '@angular/common';
import { PlotlyViaWindowModule } from 'angular-plotly.js';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    CommonModule,
    BrowserModule.withServerTransition({ appId: 'serverApp' }),
    AppRoutingModule,
    PlotlyViaWindowModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by andrefarzat** [comment]
Sorry, @tarunmishra592 . We can't support angular universal once plotly.js itself doesn't render on the server side 😿

see: https://github.com/plotly/angular-plotly.js/issues/140
