### ISSUE TITLE
How to apply animations for linear charts?

### ISSUE THREAD

**Issue by eldhoshaji** [plotly/angular-plotly.js#23]
```
import { Component } from '@angular/core';

@Component({

        selector: 'plotly-example',
        template: '<plotly-plot [data]="graph.data" [layout]="graph.layout"></plotly-plot>',
    })
    export class PlotlyExampleComponent {
        public graph = {
            data: [
                { x: [1, 2, 3], y: [2, 6, 3], type: 'scatter', mode: 'points', marker: {color: 'black'}, line: {color: 'black', width: 2, dash: 'dashdot'} },
                { x: [1, 2, 3], y: [2, 5, 3],  type: 'scatter', mode: 'points', marker: {color: 'black'}, line: {color: 'black', width: 2, dash: 'dashdot'} },        ],
            layout: {width: 320, height: 240, title: 'Plot'}
        };
    }

```
**How to show animations in linear charts to show transition of data line from starting to end point ?**

**Comment by mateusrcm** [comment]
any update on it?

**Comment by Saul-BT** [comment]
I have created a working example using the `PlotlyService` to get the `plotly` object and apply animations with it.

You can see it here: https://angular-plotly-animate.stackblitz.io

**Disadvantages:**
+ You need to retrieve the raw `plotly` object,
+ You can change the data with the `data Input()` property (`plotly-plot` component) or using the raw `plotly` object, this can produce some strange behaviors.

**Proposal:**
+ Add this functionality through an `Input()` property.

Related issues: #25  , #124
