### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by vanthome** [plotly/angular-plotly.js#231]
Please let the community know whether it is abandoned.

**Comment by rk-7** [comment]
@vanthome  I too have this question. It’s been ages there haven’t been any PR merges or commits. May be I am wrong. But the project is still at Angular 12.
I have one open PR and few more in pipeline. I hoping for someone to review them and merge.  🤞

**Comment by Abildtoft** [comment]
I'm also interested.

If there's no viable future in this repo, I'd be open to helping maintain a fork, @rk-7, based on your pull request.

**Comment by andrefarzat** [comment]
Hello @vanthome , @rk-7 and @Abildtoft . Thanks a lot for the support. 

@rk-7, I accepted the PR pumping to version 5.0.0
I will let the tests pass and generate the new version to npm
