### ISSUE TITLE
How to use Plotly.extendTraces() function in angular properly?

### ISSUE THREAD

**Issue by greyt1563** [plotly/angular-plotly.js#235]
Hey I am sharing a work that graph is changing its value every 1 seconds of interval. 
https://codepen.io/ShuvChow/pen/qBJaPMM
Can anyone suggest me how to do this in angular . 
The main issue is . I don't want to regenerate the graph after every 1 seconds of interval. 
It will not be zoomed properly and can't be properly analysis.

**Comment by andrefarzat** [comment]
Hello, @greyt1563 . You have access to Plotly instance using `PlotlyService` ( please, check : https://github.com/plotly/angular-plotly.js/blob/master/FAQ.md#how-to-access-global-plotly-object-code ).

So, you can try using `Plotly.extendTraces` directly even calling `setInterval` as you showed in your example.
Please, try it up and let us know if it works. Reopen the issue if it doesn't 😸

**Comment by greyt1563** [comment]
Can you give me the proper code and the way of how to implement this on angular?

**Comment by andrefarzat** [comment]
@greyt1563 here's an example: https://angular-p2mfmn.stackblitz.io
the code: https://stackblitz.com/edit/angular-p2mfmn?file=src/main.ts
