### ISSUE TITLE
Allow strict bundle via CDN.

### ISSUE THREAD

**Issue by ahjahjpulaj** [plotly/angular-plotly.js#237]
Hi, 
I am having issues with Content-Security-Policy using plotly via CDN, because the bundle need "unsafe-eval" policy. 
it would be useful to be able to use the strict version of the bundle.
e.g 
`PlotlyViaCDNModule.setPlotlyVersion("strict-2.24.1")`
allowing in PlotlyViaCDNModule also the "strict" keyword
`const isOk = version === 'latest' || /^\d\.\d{1,2}\.\d{1,2}$/.test(version) || /^strict-\d\.\d{1,2}\.\d{1,2}$/;`

Thanks

**Comment by andrefarzat** [comment]
@ahjahjpulaj just published the version 5.1.1. with the change you requested 😸
