### ISSUE TITLE
Error with Angular13

### ISSUE THREAD

**Issue by LeaKivi** [plotly/angular-plotly.js#239]
After installing like described, I am getting an error when compiling: 

./node_modules/angular-plotly.js/fesm2015/angular-plotly.js.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
TypeError: Cannot create property 'message' on string '...\node_modules\angular-plotly.js\fesm2015\angular-plotly.js.mjs: This application depends upon a library published using Angular version 15.2.6, which requires Angular version 14.0.0 or newer to work correctly.Consider upgrading your application to use a more recent version of Angular.

Apparently downgrading would help, but I was unable to find information of version compatibility. 

    "@angular/cdk": "~13.3.1",
    "@angular/common": "~13.3.0",
    "@angular/compiler": "~13.3.0",
    "@angular/core": "~13.3.0",
    "@angular/forms": "~13.3.0",
    "@angular/localize": "~13.3.11",
    "@angular/material": "~13.3.1",
    
    
       "@angular/cli": "~13.3.0"

**Comment by andrefarzat** [comment]
Hello @LeaKivi . First, you should update your angular application to 14.x or above. 
Even angular team doesn't support 13.x and below anymore: https://angular.io/guide/releases#actively-supported-versions

although, I checked in the commit log, the last version using angular 13.x was 5.0.0: https://github.com/plotly/angular-plotly.js/releases/tag/v5.0.0
