### ISSUE TITLE
Error: Resize must be passed a displayed plot div element.

### ISSUE THREAD

**Issue by artsnr1** [plotly/angular-plotly.js#24]
The graphs resizes fine but when I resize my window, I get the following error in the console:
"Error: Resize must be passed a displayed plot div element."
```
    <plotly-plot [data]="graph.data" [config]="graph.config" [layout]="graph.layout"></plotly-plot>
```
```
      this.graph = {
        data: data,
        layout: layout,
        config: {responsive: true}
      };
```

when I remove `config: {responsive: true}` the error disappears. Kindly let me know how to remove the error

**Comment by andrefarzat** [comment]
Could not replicated with current demo data. Please, update the library and test again. If the error persist, please reopen the issue

**Comment by ryanjackman** [comment]
I am seeing this issue also.
I can try to create a minimal reproduction example.

The issue is present in Chrome 71
I do not see the issue in Firefox 64

angular-plotly.js 1.0.1
plotly.js 1.44.1

**Comment by andrefarzat** [comment]
@ryanjackman please, do that. Use the [demo module](https://github.com/plotly/angular-plotly.js/tree/master/src/app/demo) to replicate it and open a new issue with it 😸
