### ISSUE TITLE
plotly_click event doesnt fired after newPlot

### ISSUE THREAD

**Issue by nimrco20** [plotly/angular-plotly.js#247]
Hi,
I'm calling to newPlot function in some cases, and after that it seems that the plotly_click event is not fired at all.
I'm using the property binding of (plotlyClick) in the html template.
Everything seems to work fine until the newPlot function of plotly.js is called.

Thanks for any help or an advice

**Comment by andrefarzat** [comment]
Hello @nimrco20 . Are you calling the `newPlot` function outside the angular scope? 
When you update the data, it should automatically update the graph for you (using the angular checking). Also, you could use the [`revision`](https://github.com/plotly/angular-plotly.js#basic-props) property to force to update the graph

**Comment by nimrco20** [comment]
Hi,
Thank you for your reply.
I've tried to use the revision property, but it seems that in some cases it doesn't updates the plot with the new data and layout.
I have managed to overcome this issue using this package function createPlot, which subscribing the plotly events on the new instance in the callback.

Thank you and all the team behind this package

**Comment by rajyadav-bh** [comment]
`<plotly-plot [data]="_traces" [config]="_config" [layout]="_layout"
                (plotlyClick)="onClick($event)"
            ></plotly-plot>
`
`onClick(event:any){
    console.log(event)  
  }
`

Not sure why the above code doesn't work, 
My end goal is to get the clicked x-axis label in a horizontal bar chart, I am trying with different approaches but didn't work, so just put this simple code
