### ISSUE TITLE
Facing various issues with angular16 and angular plotly

### ISSUE THREAD

**Issue by ysk3a** [plotly/angular-plotly.js#251]
Hi,
I am using angular16 with "angular-plotly.js": "^5.2.2" and "plotly.js-dist-min": "^2.27.1", 

1. i followed https://github.com/plotly/angular-plotly.js#plotly-via-window-module to then add the script in angular.json but the Plotly Via WIndow Module errors out when running ng serve saying that `"node_modules/plotly.js/dist/plotly.min.js"` does not exist. If i changed to `""node_modules/plotly.js-dist-min/plotly.min.js"` ng serve does not complain. not sure where plotly.js directory is or if this change is correct and the readme is incorrect?

2. I also tried the alternative approach mentioned in the angular-plotly.js readme https://github.com/plotly/angular-plotly.js#quick-start, and although ng serving that results in no error it however gives warning `src/app/app.module.ts depends on 'plotly.js-dist-min'. CommonJS or AMD dependencies can cause optimization bailouts.` Is this perhaps just a limitation of the plotlyjs?

3. Based on the readme doc it seems i can just send a value into the component as input as mentioned https://github.com/plotly/angular-plotly.js#basic-props ? but I can't seem to get the various themes mentioned in https://github.com/plotly/angular-plotly.js#using-themes to work. It is all just white and blue.

4. In `plotly.component.ts` i set both `yaxis` and `xaxis` properties in `layout` to have `fixedrange: true` following https://plotly.com/javascript/disable-zoom/ but chart still allows zooming with mouse drag.

5. Most importantly, I am trying to use as much plotly's types when coding and mostly got it to give me types using the typescript `Partial` keyword. However there was two cases where typescript was erroring out in `plotly.component.ts`. 
	- `PlotData` or rather the `trace1` and `trace2` variables complains the `type` property cannot be a string as it expects `PlotType`. I am not sure if this is the proper way but I temporarily casted type as `Plotly.PlotType`?
	- the `tickson: 'boundaries` does not appear to exist but the demo https://plotly.com/javascript/axes/#multi-category-axes uses that property somehow?

6. My end goal I am trying to achieve is being able to show multicategory chart as shown in https://plotly.com/javascript/axes/#multi-category-axes but im getting 
![notworkingmutlicategoryplotly](https://github.com/plotly/angular-plotly.js/assets/53593899/43cb441b-09a5-4567-901a-98ee28f8ce25)

here is reproduced issue displayed in stackblitz version of my local project https://github.com/ysk3a/angular16plotly: https://stackblitz.com/~/github.com/ysk3a/angular16plotly

**Comment by andrefarzat** [comment]
Hello @ysk3a. Merry Christmas ☃️ 

1. You're right! The lib has changed and we haven't updated the docs. Just did! 

2. This is due by `plotly.js` is bundled as amd ( or commonjs ). To avoid this, please use PlotlyViaCDNModule: https://github.com/plotly/angular-plotly.js#plotly-via-cdn-module

3. Themes is something that isn't working. I removed from the docs for now. Sorry for this.

4. This might be an issue direct in the `plotly.js` itself. Does this still happen if using it without `angular-plotly.js`?

5. The typing isn't updated as frequently as the plotly lib. Usually I recommend not using it when these issues start to happen.

6. I tried your code locally, and see that you're using `[data]="graph.data"` and  `[layout]="graph.layout"`, but regarding your data, it should be `[data]="data"` and  `[layout]="layout"`.

I am closing the issue, but feel free to reopen if anything 😸

**Comment by schoofseggl** [comment]
@ysk3a I have the same issue like you, regarding offline bundling plotly. I cannot use a CDN (must work in closed networks /offline) and get the same warning about "CommonJS or AMD dependencies can cause optimization bailouts." 

I tried the approach to load it via the window module https://github.com/plotly/angular-plotly.js#plotly-via-window-module, but still get the same warning. I am not sure because we use angular components, not modules. 

I wonder if you did solve it and how?

**Comment by schoofseggl** [comment]
I don't really recall when this error happend and how we fixed it. But we still use it and finally integrated it this way: 

in angular.json somewhere in ./../architect/build/options: 

`   "scripts": ["node_modules/plotly.js-dist-min/plotly.min.js"],`

in package json 
```
"angular-plotly.js": "^6.0.0",
"plotly.js-dist-min": "^2.35.2",
```
as dev dependency:   
`  "@types/plotly.js-dist-min": "^2.3.4",`

in the angular component: 

```
import { PlotlyService, PlotlyViaWindowModule } from 'angular-plotly.js';
import * as PlotlyJS from 'plotly.js-dist-min';
```

and 

```
@Component({
  ...
  imports: [
    ..
    PlotlyViaWindowModule
   ...
  ],
})
```
