### ISSUE TITLE
Memory leak when using newPlot or update

### ISSUE THREAD

**Issue by Alterock13** [plotly/angular-plotly.js#28]
Hi,

I'm running Plotly as a way to display data coming from a database, with around 800 new points/second.
As I let my application running, I notice that my RAM usage is steadily inscreasing, eating up to 10Gb of RAM over the course of half an hour.

Looking at Plotly issues on GitHub, I've noticed that Plotly users have reported that it was happening to them [1755](https://github.com/plotly/plotly.js/issues/1755) but I think that a recent patch was supposed to fix that.

I've tried both newPlot and update as a way to refresh my plot. Here's my current code :  
```
       this.interval = interval(1000);
       this.subscribe = this.interval.subscribe(val => {
                this.traces = [this.data[0]];
                this.lastUpdateChange.emit(new Date());
                if(this.highThresholdEnabled || this.lowThresholdEnabled){
                    this.onThresholdChange();
                } else{
                    Plotly.update(
                        this.layout['title'], 
                        this.traces, this.layout, 
                        this.options)
                }});
```
I'm running out of ideas for this problem, does anyone know how I could stop this memory leak? 

Thanks in advance.

**Comment by andrefarzat** [comment]
This one is even hard to simulate. When you say memory leak, you mean the browser freezes ?
What Plotlyjs version you're using ?

**Comment by andrefarzat** [comment]
@Alterock13 just updated the lib to use `Plotly.react` instead of `Plotly.newPlot` in the update method of the angular component. Please, update to version `0.2.2` and check if this still persists. In parallel, I will create an example on our demo to replicate this behaviour

**Comment by Alterock13** [comment]
Thanks !
I'll give it a go tomorrow and keep you posted on the results.

**Comment by Alterock13** [comment]
Hi 

So I've tried updating and running the app again. And I still have a rising memory consumption.
I'll keep testing with different parameters and keep you posted if there are any changes.

**Comment by andrefarzat** [comment]
@Alterock13 I could not replicate this issue. I might not have tried correctly, so I added a "memory-leak" page on the demo with your example to try to simulate it. I left it running on my mac using opera and the memory didn't grew much in about 5 minutes which I watched. 
I am closing this issue for now, but please, check the code I just pushed on master ( https://github.com/plotly/angular-plotly.js/commit/238fcc9c49879e981c7313d3688925174490bdbf ) and update it if necessary and create a PR, so I can see the issue and debug it better 😸
