### ISSUE TITLE
lasso-select not showing the lasso outline most of the time

### ISSUE THREAD

**Issue by zhihua-chen** [plotly/angular-plotly.js#3]
Fresh ng new project. Simple scatter plot. When I use the lasso select tool, dragging selects the points but does not leave an outline of the lasso, most of the time. Same behavior, either with 0.1.10 or 0.1.9.

```
        data: [
            { x: [1,3,5,4] , y: [4,5,3,6], type: 'scatter', mode: 'markers', marker: {color: 'red'} },
        ]

        layout: {autosize:true, title: 'A Fancy Plot'}

```

**Comment by andrefarzat** [comment]
@zhihua-chen Could not replicate the issue. What is happening is the lasso isn't appearing when selecting ?

**Comment by zhihua-chen** [comment]
@andrefarzat Yup. The points are selected and highlighted, but the lasso is not showing up.

**Comment by andrefarzat** [comment]
@zhihua-chen I could not replicate the problem ( or I misunderstood it ). A print showing the tool working with the date you provided:

<img width="1403" alt="angular-plotly-print" src="https://user-images.githubusercontent.com/649219/39611708-2a8341c0-4f30-11e8-9c32-287715dcfcae.png">

Is that correct ?

**Comment by andrefarzat** [comment]
@zhihua-chen  I can confirm the lasso isn't showing up. I am still on the issue to figure out what might happening

**Comment by andrefarzat** [comment]
Things should work as expected on version `1.0.0`. Please update `angular-plotly.js` to `1.0.0`. If it continues, please reopen the issue

**Comment by jorrog** [comment]
Hi andrefarzat, 
I'm on ver. 1.0.1 but I still can't see the selecting outline on lasso and range selections when mode: Markers.

Can you confirm that this issue is fixed in that version.

thanks
