### ISSUE TITLE
Plot not displayed until hovered

### ISSUE THREAD

**Issue by mebibou** [plotly/angular-plotly.js#32]
Just added the plotly on my angular application on `angular@7.0.4`. I am loading data from an API:
```
// html
<plotly-plot [data]="chartData" [layout]="graphLayout"></plotly-plot>
// ts
fetch().then(data => this.chartData = data)
```
When the data is fetched, the graph does not display anything, but as soon as I hover the chart then it appears.

I have tried using plotly directly like so:
```
// html
<div id="plot"></div>
// ts
import * as Plotlyjs from 'plotly.js/dist/plotly.min.js';
fetch().then(data => Plotlyjs.plot(document.getElementById('plot', data)))
```
and it works without having to hover the chart

**Comment by mebibou** [comment]
Using:
```ts
class Component {
  constructor(private ref: ApplicationRef) {}

  async update() {
    const data = await fetch();
    this.chartData = data;
    this.ref.tick();
  }
}
```
will display the graph, is the update of data not in a zone?

**Comment by andrefarzat** [comment]
Hello @mebibou , what is this `fetch` function? Looks like it is outside the zone, for the chart is updated once `data` is changed in another context (i.e.: via hover or click events). Does the same happen if you use angular native `http` module ?

**Comment by mebibou** [comment]
@andrefarzat oh it's actually a simple `HttpClient.get` so yeah it's definitely in the zone, and when using other charting library I didn't have this update issue

**Comment by andrefarzat** [comment]
@mebibou I am trying to replicate, but looks ok to me on my simple test. I just pushed (on master) an example on the demo. May I ask you to git clone this repo, install and run it locally and see if the ajax example works ok ? ( https://github.com/plotly/angular-plotly.js#development )

**Comment by andrefarzat** [comment]
If it is still an issue, please reopen it
