### ISSUE TITLE
lasso-select and range-select  not showing the select outline on mode: markers

### ISSUE THREAD

**Issue by jorrog** [plotly/angular-plotly.js#39]
Using ver. 1.0.1 the lasso-select and range-select  not showing the select outline on mode: markers.
When the mode is Lines everything works as expected.

**Comment by andrefarzat** [comment]
@jorrog what module are you using? `PlotlyModule`, [`PlotlyViaCDNModule`](https://github.com/plotly/angular-plotly.js#plotly-via-cdn-module) or [`PlotlyViaWindowModule`](https://github.com/plotly/angular-plotly.js#plotly-via-window-module) ?
This question is important, for I am afraid that angular's minifier screws up `plotly.js` code

**Comment by andrefarzat** [comment]
@jorrog please, test with other module ( [`PlotlyViaCDNModule`](https://github.com/plotly/angular-plotly.js#plotly-via-cdn-module) for example) and let us know if the issue persists

**Comment by jorrog** [comment]
@andrefarzat same thing. When i have only line plots the selection is working fine, but when I put the scatter mode the selection outline is gone.

**Comment by andrefarzat** [comment]
Looks like the issue is not happening. I dunno if it was in `plotly.js` itself. I will close this issue. Please reopen if you're still seeing the issue
