### ISSUE TITLE
Feature request 'onHover' event

### ISSUE THREAD

**Issue by matteson** [plotly/angular-plotly.js#4]
I'm really excited about this component! I currently depend on home-rolled access to the plotly_hover event. To adopt this, I'd need the onHover() event similar to the React plotly component.

Any ideas on timeline for events?

**Comment by andrefarzat** [comment]
Hi @matteson, it is in our roadmap, although we don't know exactly the best interface for these events.
The most simple would be adding the `plotly_*` events direct in the component tag. Example:
```html
<plotly-plot [data]="graph.data" [layout]="graph.layout" (hover)="graph.onHover()"></plotly-plot>
```
you think is ok ?

**Comment by matteson** [comment]
That interface would meet the needs of my use case.

**Comment by andrefarzat** [comment]
@matteson I've added the events as properties on the component. Check it here: https://github.com/plotly/angular-plotly.js#event-handler-props
Please, update to `0.1.13` to get changes.

If you have problems, please reopen this issue 😸

**Comment by matteson** [comment]
Thanks @andrefarzat !

I was able to get this up and running. Here's a demo of how I'm using the hook in case you're interested: https://github.com/matteson/plotly-hover-demo

**Comment by andrefarzat** [comment]
@matteson this is a very nice use case ! Combining two graphs like that. Thanks a lot for this example 😸

**Comment by scozma** [comment]
HI @andrefarzat - I downloaded your demo app but I was not able to add other events. For example, I added the **selected** event into the HTML: 
```
<plotly-plot [data]="dataEndpoint" [layout]="layoutEndpoint" (hover)="hover($event)" (unhover)="unhover($event)" (selected)="selected($event)"></plotly-plot>
```
and this into the component:
```
selected(event: any): void {
    console.log(event);
  }
```
but the **console.log()** never gets called. Can you please advise what could be wrong? Thanks!
