### ISSUE TITLE
Can't get autosize to change plot height

### ISSUE THREAD

**Issue by benwhitman** [plotly/angular-plotly.js#48]
As seen in 

https://codesandbox.io/embed/52nw4n5n1x?fontsize=14&codemirror=1

 am trying to get the plot to auto size to both the height and width of the containing element. The width changes perfectly but the height seems to be locked at 450px. I am using [useResizeHandler] =true.

**Comment by andrefarzat** [comment]
@benwhitman height in css is always hard for it is not possible to know what `100%` means. In your example, no parent element has a defined height, and by definition, an element with no height specified has its content as height. So, if you defined  a height on a parent element ( such the below print from your example ) it works as expected.
<img width="1736" alt="screen shot 2019-03-05 at 21 15 50" src="https://user-images.githubusercontent.com/649219/53846580-39d8ed80-3f8c-11e9-9939-0011334357d7.png">

But I suppose you want to that to work without forcing any height anywhere right ? if yes, well, try creating a layout with the content you expect and see if the `height: 100%` adapts as expected. (See this example below where I added `<br />`s to increase the height of the parent element and the graph follows)
<img width="1636" alt="screen shot 2019-03-05 at 21 24 31" src="https://user-images.githubusercontent.com/649219/53846818-2b3f0600-3f8d-11e9-88fb-54de9d78a726.png">

Thanks a lot for creating an example of your issue. It really helped to understand what you meant. If you still have the doubt, please reopen the issue 😸
