### ISSUE TITLE
Customize the plotly.js bundle

### ISSUE THREAD

**Issue by liefra** [plotly/angular-plotly.js#5]
Is there a way to customize the plotly.js bundle or load plotly.js via CDN? 

Would be great to reduce the app size as a new Angular 6 app with angular-plotly.js is already 2.83 MB.

**Comment by arlowhite** [comment]
I came-up with a solution in my [angular-plotly-react](https://github.com/arlowhite/angular-plotly-react) library, which allows you to asynchronously load plotly.js.
`PlotlyModule.forRoot()` seems like the right place to configure this kind of thing.
See: [PlotlyModule.forRoot](https://github.com/arlowhite/angular-plotly-react/blob/master/projects/angular-plotly-react/src/lib/plotly.module.ts)
and [PlotlyService](https://github.com/arlowhite/angular-plotly-react/blob/master/projects/angular-plotly-react/src/lib/plotly.service.ts)

Feel free to copy this code if it's useful, it's MIT licensed.

**Comment by nicolaskruchten** [comment]
@andrefarzat you should consider letting people pass in their own `plotly` like we do in React-land :)

**Comment by andrefarzat** [comment]
it arrived! Version `1.0.0` supports getting the Plotly object from window or loading via CDN. Please, check the doc](https://github.com/plotly/angular-plotly.js#customizing-the-plotlyjs-bundle) about 😸

**Comment by alwaysprep** [comment]
@andrefarzat  PlotlyViaWindowModule example is a bit hard to understand for the people who are new to the angular community. Can you give a full example in the readme file?

**Comment by andrefarzat** [comment]
@alwaysprep I created an issue for it. Will work on it this weekend 😃
