### ISSUE TITLE
Specify bundle type with CDN module.

### ISSUE THREAD

**Issue by jraadt** [plotly/angular-plotly.js#53]
You can pass in a version like 1.4.3, but you can't specify a specific bundle like "basic". You always have to get the full Plotly. It would be nice to be able to specify a bundle to retrieve from the CDN.

**Comment by andrefarzat** [comment]
Hello @jraadt . There is this method to validate the string which is the plotly version for CDN: https://github.com/plotly/angular-plotly.js/blob/master/src/app/plotly-via-cdn/plotly-via-cdn.module.ts#L16

May I ask you to suggest a version of this function which accept what you're expecting and create a PR ? 😸
