### ISSUE TITLE
ERROR in node_modules/angular-plotly.js/src/app/plotly-via-cdn/plotly-via-cdn.mo dule.d.ts(8,10): error TS2315: Type 'ModuleWithProviders' is not generic.

### ISSUE THREAD

**Issue by AbhijeetGiram** [plotly/angular-plotly.js#58]
Can anyone know how to resolve this error?
ERROR in node_modules/angular-plotly.js/src/app/plotly-via-cdn/plotly-via-cdn.mo
dule.d.ts(8,10): error TS2315: Type 'ModuleWithProviders' is not generic.

Followed below link
https://github.com/plotly/angular-plotly.js#quick-start

angular6 project

**Comment by andrefarzat** [comment]
May I ask you to try using angular 7 project ?

**Comment by AbhijeetGiram** [comment]
Migration is not possible for a while. Can't we fixed it in angular 6 only?

**Comment by andrefarzat** [comment]
I forced to create a project using `@angular/cli` version 6.2.9 and once I installed both `angular-plotly.js` and `plotly.js` dependencies via `npm i`, I've got old versions of both libraries. I dunno if this is your issue, but I am afraid this is or `angular-plotly.js` version or typescript version issue. May I ask you to show the `package.json` of this project ?

**Comment by AbhijeetGiram** [comment]
{
  "name": "demo",
  "version": "1.1.0",
  "private": true,
  "scripts": {
    "ng": "ng",
    "start": "ng serve"
  },
  "dependencies": {
    "@angular/animations": "6.0.3",
    "@angular/common": "6.0.3",
    "@angular/compiler": "6.0.3",
    "@angular/core": "6.0.3",
    "@angular/forms": "6.0.3",
    "@angular/http": "6.0.3",
    "@angular/platform-browser": "6.0.3",
    "@angular/platform-browser-dynamic": "6.0.3",
    "@angular/router": "6.0.3",
    "@ng-select/ng-select": "^1.5.2",
    "angular-plotly.js": "^1.2.0",
    "angular2-uuid": "1.1.1",
    "bootstrap": "3.3.7",
    "classlist.js": "^1.1.20150312",
    "connect-history-api-fallback": "1.5.0",
    "core-js": "2.5.4",
    "cors": "2.8.5",
    "d3": "3.5.17",
    "d3-scale-chromatic": "^1.3.3",
    "device-uuid": "^1.0.4",
    "http-status": "1.3.1",
    "ibantools": "2.0.0",
    "jwt-decode": "^2.2.0",
    "moment": "^2.24.0",
    "ng5-slider": "^1.1.13",
    "ngx-xml2json": "1.0.2",
    "plotly.js": "^1.47.2",
    "primeicons": "1.0.0",
    "primeng": "6.1.7",
    "rxjs": "6.3.3",
    "rxjs-compat": "6.3.3",
    "web-animations-js": "^2.3.1",
    "xml-js": "1.6.9",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.13.8",
    "@angular/cli": "6.0.8",
    "@angular/compiler-cli": "^7.2.13",
    "@angular/language-service": "6.0.3",
    "@jongleberry/json-check": "1.0.0",
    "@types/jasmine": "2.8.6",
    "@types/jasminewd2": "2.0.3",
    "@types/node": "^10.12.6",
    "autoprefixer": "^9.5.1",
    "codelyzer": "4.2.1",
    "jasmine-core": "3.3.0",
    "jasmine-spec-reporter": "4.2.1",
    "json-check": "0.1.1",
    "karma": "^4.1.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-coverage-istanbul-reporter": "2.0.0",
    "karma-jasmine": "1.1.1",
    "karma-jasmine-html-reporter": "1.4.0",
    "lint-staged": "8.0.4",
    "markdownlint": "0.11.0",
    "markdownlint-cli": "^0.15.0",
    "protractor": "5.4.1",
    "pug": "2.0.3",
    "pug-plain-loader": "1.0.0",
    "rxjs-tslint-rules": "4.11.0",
    "stylelint": "9.8.0",
    "stylelint-a11y": "1.1.9",
    "stylelint-config-standard": "18.2.0",
    "stylelint-high-performance-animation": "1.1.1",
    "stylelint-no-indistinguishable-colors": "1.2.1",
    "stylelint-no-unsupported-browser-features": "3.0.2",
    "ts-node": "5.0.1",
    "tslint": "5.11.0",
    "typescript": "2.7.2"
  }
}

Here is it. package.json

**Comment by andrefarzat** [comment]
@AbhijeetGiram I reviewed the code and looks like the `ModuleWithProviders` is not necessary anymore since we can't call functions/methods inside module definitions (because of aot). I refactored the code to remove'm. Please, update to version `1.3.0` and check if the issue is fixed 😸
