### ISSUE TITLE
Plot not updating

### ISSUE THREAD

**Issue by sadoMasupilami** [plotly/angular-plotly.js#59]
Hi,

I am trying to show livedata from an API in a plotly graph updating 1-2 times per second.
Sadly I don't manage to update the graph, the code below draws the initial graph, than once more after 20 updates and than never again. Selecting or deselecting one of the traces draws everything correctly.
Any help what I am missing or if there is some bug present would be really appreciated.

HTML:
`<plotly-plot [data]="graph.data" [layout]="graph.layout" useResizeHandler="true"></plotly-plot>
`

TS:
~~~~
import {Component, OnDestroy, OnInit} from '@angular/core';
import {LiveMeasurementsService} from '../../services/live-measurements.service';
import {LiveData} from '../../model/live-data';

@Component({
  selector: 'app-live',
  templateUrl: './live.component.html',
  styleUrls: ['./live.component.css'],
})
export class LiveComponent implements OnInit, OnDestroy {

  private timestamps: Date[];
  private y1: number[];
  private y2: number[];
  private y3: number[];
  private graph;

  private timeoutID;

  constructor(public live: LiveMeasurementsService) {
  }

  ngOnInit() {
    this.timestamps = [];

    this.y1 = [];
    this.y2 = [];
    this.y3 = [];

    this.graph = {
      data: [
        {x: this.timestamps, y: this.y1, type: 'scatter'},
        {x: this.timestamps, y: this.y2, type: 'scatter'},
        {x: this.timestamps, y: this.y3, type: 'scatter'},
      ],
      layout: {
        autosize: true,
        title: 'Live Plot',
        font: {family: 'Roboto, "Helvetica Neue", sans-serif'},
        margin: {t: 50, b: 20, l: 40, r: 40},
      }
    };

    this.startUpdate();
  }

  startUpdate() {
    this.timestamps.push(new Date());
    this.y1.push(Math.random());
    this.y2.push(Math.random());
    this.y3.push(Math.random());
    this.timeoutID = setTimeout(() => this.startUpdate(), 1000);
  }

  updateGraph(values: LiveData) {

  }

  ngOnDestroy(): void {
    clearTimeout(this.timeoutID);
  }
}

~~~~

**Comment by andrefarzat** [comment]
Hello @sadoMasupilami I just pushed a fix. Once circle ci is happy with it I will publish version 1.3.1 with the fix.

The issue was related to `Plotly.react` function which doesn't behave as we aspect with arrays. Please, see the docs: https://plot.ly/javascript/plotlyjs-function-reference/#plotlyreact

The fix was to add the `layout.datarevision` counter to force it update once angular detects that the data (or layout) has changed

**Comment by andrefarzat** [comment]
@sadoMasupilami just published. Please, update to version 1.3.1 😸

**Comment by sadoMasupilami** [comment]
Succesfully tested today in the morning. 
Thank you for the extremly quick fix and have a nice day!

**Comment by nitish-solabannavar** [comment]
Hey @andrefarzat, I tried using the exact same code to show livedata from an API in a plotly graph but the graph isn't updating with the live data. I am using plotly version 1.58.2
How can i fix it?
