### ISSUE TITLE
config not used?

### ISSUE THREAD

**Issue by zhihua-chen** [plotly/angular-plotly.js#6]
```
  <plotly-plot [data]="[
            { x: [1, 2, 3], y: [2, 6, 3], type: 'scatter', mode: 'lines+points', marker: {color: 'red'} },
            { x: [1, 2, 3], y: [2, 5, 3], type: 'bar' }]"
               [config]="{displayModeBar: false}"></plotly-plot>
```

Trying to hide the mode bar but it's not having any effect.

**Comment by andrefarzat** [comment]
@zhihua-chen damn ... a regression... Just published a release and wrote down to write a test to guarantee this won't happen. 

Please, update to 0.1.14 and thanks to report 😸
