### ISSUE TITLE
PlotlyViaCDNModule gives Error: Peer dependency plotly.js isn't installed

### ISSUE THREAD

**Issue by frankadrian** [plotly/angular-plotly.js#61]
Hi good Sir,

I want to change form PlotlyModule to PlotlyViaCDNModule.

If I change to PlotlyViaCDNModule in my modules imports I get this error in the browser console:

`angular-plotly.js.js:416 Error while plotting: Error: Peer dependency plotly.js isn't installed`

Prior to this change my charts where rendering fine!

Versions:

@angular/cli@7.3.8
angular-plotly.js@1.3.1
plotly.js@1.47.4

Module:

```
... imports

PlotlyViaCDNModule.plotlyVersion = '1.5.0'; // can be `latest` or any version number (i.e.: '1.4.3')
PlotlyViaCDNModule.plotlyBundle = 'basic'; // optional: can be null (for full) or 'basic', 'cartesian', 'geo', 'gl3d', 'gl2d', 'mapbox' or 'finance'


const routes: Routes = [
  {
    path: '',
    component: AnalyseComponent,
  }
];

@NgModule({
  declarations: [AnalyseComponent, CrcBarChartComponent],
  imports: [
    CommonModule,
    PlotlyViaCDNModule,
    MatCardModule, MatButtonModule,
    RouterModule.forChild(routes)
  ],
  exports: [
    RouterModule
  ]
})
export class AnalyseModule { }
```

Kind Regards, 
Frank

**Comment by andrefarzat** [comment]
@frankadrian you're right. It's a bug. The fix is coming in: #62

**Comment by andrefarzat** [comment]
@frankadrian Please, update to version `1.3.2`. Reopen this if the issue continues. Thanks a lot for reporting the bug 😸

**Comment by frankadrian** [comment]
Thanks @andrefarzat for the quick fix, its working 😎
