### ISSUE TITLE
Export plot with custom settings

### ISSUE THREAD

**Issue by 3ddy2207** [plotly/angular-plotly.js#66]
Hello,

I would like to export the plot with custom settings like type,height and width. 
For plotly.js I would simply need to include the following:
`      modeBarButtonsToAdd: [
        {
          name: 'Download plot as a svg',
          icon: Plotly.Icons.camera,
          click: function(gd) {
            Plotly.downloadImage(gd, { format: 'svg' });
          }
        },
        {
          name: 'Download plot as a png',
          icon: Plotly.Icons.camera,
          click: function(gd) {
            Plotly.downloadImage(gd, {
              format: 'png',
              height: 1800,
              width: 1000,
              filename: 'Auslegungsblatt'
            });
          }
        }
      ]
`
Should I additionally use plotly js in my angular project to be able to use methods such as "Plotly.downloadImage" or what would be the propper way?

Thanks

**Comment by infrarosso78** [comment]
Same exact question here

**Comment by andrefarzat** [comment]
Hello, @3ddy2207 and @infrarosso78 ,

You can access `Plotly` global object via `PlotlyService`. Like this:

```js
import { PlotlyService } from 'angular-plotly.js';

export class PageComponente {
    constructor(public plotlyService: PlotlyService) {}


    public downloadGraph() {
        const graphDiv = this.plotlyService.getInstanceByDivId('the-id');
        this.plotlyService.getPlotly().downloadImage(graphDiv, {...});
    }
}
```
it's needed that you add the `divId` property on the `<plotly-plot>` component to be able to access it on ts side.

Let me know if this solves the doubt 😸

**Comment by infrarosso78** [comment]
Hi @andrefarzat ! First of all thanks a lot. 
I've still a little problem if i do what you said.  I get an "Error: DOM element provided is null or undefined"
here is my code (it's pug):
`.plot-container(*ngIf="graph && !loading")`
`plotly-plot#real([data]="graph.data", [layout]="graph.layout", [config]="graph.config", (hover)="plotyOver($event)", [useResizeHandler]="true", [style]="{position: 'relative', width: '100%', height: '100%'}")`

and  
`const graphDiv = this.plotlyService.getInstanceByDivId('real');`
`this.plotlyService.getPlotly().downloadImage(graphDiv, {format: 'png', width: 1024, height: 800, filename: 'test.png' });`

**Comment by andrefarzat** [comment]
Hello @infrarosso78 , just change `<plotly-plot id="real" ` to `<plotly-plot divId="real" ` so `const graphDiv = this.plotlyService.getInstanceByDivId('real');` will work as expected 😸

**Comment by infrarosso78** [comment]
Amazing! thanks. I thought the divId was the div id :D :D 
Thanks again!

**Comment by andrefarzat** [comment]
Great to hear! Please, reopen this issue if you need more help 😸

**Comment by bumbeishvili** [comment]
@andrefarzat  I think,  you should include "how to access global Plotly object code" into the readme.md file 

I had to dig into issues in order to find relevant code

**Comment by andrefarzat** [comment]
@bumbeishvili Good suggestion. Issue #92 created 😸
