### ISSUE TITLE
QQ: How we can download the graph into png file.

### ISSUE THREAD

**Issue by kumargauravin** [plotly/angular-plotly.js#67]
How to use Plotly.downloadImage through angular plotly.
We have a requirement to download the graphs shown through angular plotly so far.

**Comment by andrefarzat** [comment]
@kumargauravin You can access the `Plotly` object via `PlotlyService` using `getPlotly` method. Please check this comment on a previous issue: https://github.com/plotly/angular-plotly.js/issues/66#issuecomment-496560984

**Comment by andrefarzat** [comment]
Gonna close this issue, but feel free to reopen if you're still in doubt 😸

**Comment by kumargauravin** [comment]
Hi Farzat,
I was able to download using divId and @ChildView. But some problems.

We are rendering overlapping plots where upto 500 lines are plotted... with option of say 25 line vs all lines mode. As we re-plot the data by adding value to [data] and then try to use @ChildView sometimes the reference does not get refreshed and moves to null. 

If we do it via divId it works but the problem is if I just want to add a title or make some changes to download only image changes done to config or layout are not reflected on divId but are available through @ChildView.

Is thr something we are doing wrong?
Also, what is the plan for animations?

**Comment by andrefarzat** [comment]
Hello @kumargauravin , it's hard to understand what issue you're facing. But I suppose you're using `@ChildView` inside your component to access the `PlotComponent`. I would not recommend using `@ChildView` for it works getting the angular reference, and I believe we want the Plotly reference here. Also, if your component is rendered mora then once, it would be better using a dynamic string as id to be passed to `divId`, so there is no conflicts when you call `PlotlyService.getInstanceByDivId`.

Although, I think I misunderstood your problem. Would you show me the code or an example ?

**Comment by kumargauravin** [comment]
Hi,
I cannot paste a sample will see if I can create some example outside later.

Using divId if I have to download with a title but display without, the
graph does not updates with title before download. ChildView though seems
to be working here is the conflict, I also want to use divID but this
functionality is not working.

Regards,
Kumar
