### ISSUE TITLE
(update) output binding does not return graphDiv.

### ISSUE THREAD

**Issue by EdSci** [plotly/angular-plotly.js#71]
Dear all,
Thank you so much for the amazing work!
I was trying to find a way to save a static image (png) of my plot following the instructions from the official page [https://plot.ly/javascript/static-image-export/]. To get the divHtml, I have decided to use the following approach:

```
      <plotly-plot [data]="traces" [layout]="layout"  [revision]="revision" 
                          (update)="onGetTheDiv($event)" >
     </plotly-plot>
```

However when I use console.log() to see the  $event, I cannot find any reference to  graphDiv.
I see only the object.
{data: [Trace], frames: [ ]    layout: {datarevision: 3, ...., title: {…}, xaxis: {…}, …}

Have I misunderstood the API reference about 'update'?
Is this behaviour correct?  Does angular-plotly  have a better approach to get the plot snapshot programmatically? 

Best regards
CB

**Comment by andrefarzat** [comment]
Hello, @EdSci , the `update` event only receives the `graph` object. Although, you can set and get the reference id via angular itself. Like this:
```html
<plotly-plot [data]="..." divId="the-id"></plotly-plot>
```

Then, you can download the image like:
```ts
import { PlotlyService } from 'angular-plotly.js';

export class PageComponente {
    constructor(public plotlyService: PlotlyService) {}


    public downloadGraph() {
        const graphDiv = this.plotlyService.getInstanceByDivId('the-id');
        this.plotlyService.getPlotly().downloadImage(graphDiv, {...});
    }
}
```

see this thread as reference: https://github.com/plotly/angular-plotly.js/issues/66#issuecomment-496560984

**Comment by EdSci** [comment]
I see.
I misunderstood the API reference:   (update) =   Function(figure, graphDiv).
Everything is clear now.
Thank you andrefarzat!
