### ISSUE TITLE
Expose "plotly_relayouting" event

### ISSUE THREAD

**Issue by Mesya82** [plotly/angular-plotly.js#72]
Plotly.js team added very useful event "plotly_relayouting" in v1.48.0(https://github.com/plotly/plotly.js/issues/2082). I think most of us will want to have this event to be exposed in PlotComponent alongside with many other events. I will make Pull request with this feature if I will have time

**Comment by andrefarzat** [comment]
@Mesya82 amazing. I will be waiting your pull request. Please, don't forget to add an example on the demo page as a test 😸

**Comment by andrefarzat** [comment]
@Mesya82 please, review the PR #77 😺
