### ISSUE TITLE
rowBlock undefined

### ISSUE THREAD

**Issue by keithchanyk** [plotly/angular-plotly.js#73]
Hi, I have an issue of rowBlock undefined, did anyone face this problem?
![image](https://user-images.githubusercontent.com/50238840/63040574-4cbafb00-bef8-11e9-8e8e-6fa287fda29c.png)

Hope anyone could help me, thanks!!

**Comment by antoinerg** [comment]
Hello @keithchanyk, can you provide us with more details? What did you try to plot?

**Comment by andrefarzat** [comment]
Closed for inactivity. Please reopen if necessary
