### ISSUE TITLE
Error when building against 1.4.x: export 'ɵɵdefineInjectable' was not found in '@angular/core'

### ISSUE THREAD

**Issue by niklaskarl** [plotly/angular-plotly.js#79]
There seems to be an issue with versions 1.4.x. When upgrading the project to these versions I get the following warning when building with Angular 7.2 which ultimately leads to an runtime error in the browser.

WARNING in ./node_modules/angular-plotly.js/fesm5/angular-plotly.js.js 128:36-54
export 'ɵɵdefineInjectable' was not found in '@angular/core'

Opening this file I find the import with the strange 'ɵ' characters.

**Comment by andrefarzat** [comment]
Hello, @niklaskarl . I believe this is an angular issue related to what versions you have installed. Mind posting the package.json here ?
also, is this a fresh install?

**Comment by rbschiefer** [comment]
I have the same issue after setting up a fresh project with angular cli 8.3.3... also tried updating to angular version 8.2.5 (current stable): issue remains.

**Comment by andrefarzat** [comment]
@niklaskarl @rbschiefer still believe this is an angular issue. I already reported a similar error in a another package before: https://github.com/Nolanus/ngx-page-scroll/issues/363

Maybe uninstalling and installing the libraries with current versions might fix regarding this: https://github.com/angular/angular/issues/30413#issuecomment-523194271

**Comment by TajMahPaul** [comment]
I was having the same issue with 1.4.x and angular 7. I had to use 1.3.2 for it to work with angular 7.

**Comment by rbschiefer** [comment]
@andrefarzat uninstalling/installing libraries did not work!
@TajMahPaul thx, going back version of angular-plotly to 1.3.2 solved my issue, but is only a workaround I guess!

**Comment by TajMahPaul** [comment]
> @andrefarzat uninstalling/installing libraries did not work!
> @TajMahPaul thx, going back version of angular-plotly to 1.3.2 solved my issue, but is only a workaround I guess!

It seems like v1.4.x is dependant on angular 8 and v1.3.2 on angular 7. Can you comment @andrefarzat ? In angular 8 I know they renamed `defineInjectable` to `ɵɵdefineInjectable`. Hence, the discrepancy.

**Comment by andrefarzat** [comment]
@TajMahPaul you're right about the dependencies. And true that they renamed 
`defineInjectable` to `ɵɵdefineInjectable`.
With this scenario, looks like we should have two versions ( one `angular-plotly.js` for angular 7.x and another for 8.x). What do you suggest we should do?

**Comment by TajMahPaul** [comment]
@andrefarzat I would suggest making it clear somewhere in your documentation which version is recommended for version 'x' of angular. Maybe make it part of the npm install process? I can help with whatever you think is best.

**Comment by andrefarzat** [comment]
Just added a note on the FAQ
