### ISSUE TITLE
Pause button in demo frames not working

### ISSUE THREAD

**Issue by caiofcm** [plotly/angular-plotly.js#81]
I tried to use the animation buttons as in plotly documentation and I could not make the Pause button to work properly (stop the animation).

Checking the demo "frames" I notice that the Pause button does not work as well. 

Any help in this issue? Thank you!

**Comment by andrefarzat** [comment]
@caiofcm you're right. The pause button and even the animation aren't working on the demo. Will look after this

**Comment by andrefarzat** [comment]
The animation is working, but the pause button still doesn't. I will keep digging on it

**Comment by andrefarzat** [comment]
I finally could figure out what is happening. `angular-plotly.js` calls `Plotly.react` every time there is a change on `data` or `layout` objects, and both play and pause actions causes one of them to change triggering the graph update. This is breaking the pause action (dunno how tbh).

To solve this (and other issues related to unexpected graph updating), I added the properties `updateOnDataChange` and `updateOnLayoutChange` to determine if the lib should update on these objects change or not. With both set to `false`, the pause button works 😸
