### ISSUE TITLE
Unable to make heatmap and cant find tutorials for angular plotly

### ISSUE THREAD

**Issue by HemanthKalathil** [plotly/angular-plotly.js#82]
I am trying to make a heat map and I don't know where to find tutorials for angular plotly. I found the plotly.js tutorial: https://plot.ly/javascript/heatmaps/ and they have a guide to make exactly what I need. My project uses angular 6.2.9 and typescript that's why I thought I need to use this. I am unsure of what to do. Sorry for the question. 
I tried doing this:

import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-optimization-heat-map',
  template: `
    <plotly-plot [data]="graph.data" [layout]="graph.layout" 
       [useResizeHandler]="true" [style]="{position: 'relative', width: '100%', height: '100%'}">
    </plotly-plot>`,
  styleUrls: ['./optimization-heat-map.component.css']
})
export class OptimizationHeatMapComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

  public graph = {
    data: [
      {z: [[1, 20, 30, 50, 1], [20, 1, 60, 80, 30], [30, 60, 1, -10, 20]],
      x: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      y: ['Morning', 'Afternoon', 'Evening'],
      type: 'heatmap'}
    ],
    layout: {autosize: true, title: 'A Fancy Plot'}
};
}
but it just gives me a line graph for some reason

**Comment by HemanthKalathil** [comment]
Sorry for asking so many questions but I dont know where else to turn to this seems like the best source for angular plotly

**Comment by HemanthKalathil** [comment]
figured it out

**Comment by patricknee** [comment]
Would be helpful if you included your solution. Thanks.

**Comment by bluppfisk** [comment]
Most likely the plotly version that comes installed with angular-plotly/is installed is the basic version which does not include heatmap support. The solution is to:

**install plotly 2.x**
`npm install plotly.js-dist-min` (or any of the smaller bundles containing the type of trace you need, e.g. cartesian`

**in app.module.ts:**

```typescript
import { PlotlyModule, PlotlyViaWindowModule } from 'angular-plotly.js';
import * as PlotlyJS from 'plotly.js-dist-min';
PlotlyModule.plotlyjs = PlotlyJS;
```

**Comment by johnasherrayan** [comment]
Any update on this or any working example? (heatmap with angular plotly)

**Comment by samerkassem82** [comment]
Funny how he didn't care of help others.
