### ISSUE TITLE
Data does not display if data type changes

### ISSUE THREAD

**Issue by cameronwaterman** [plotly/angular-plotly.js#83]
Steps to reproduce:

1. Create plot initialized with numeric data on the x
2. Change data bound to plot with date formatted x data

The numeric x data shows, but when changing to date formatted data, nothing shows up.
The same date formatted data does show up if it is the first data displayed on the graph.

Interestingly, a different issue is presented if the order of operations is reversed. In the case where the date formatted x data is displayed on the graph first, and then changed to numeric x data, the previous data remains on the graph, overlayed on the new data, even though the old data is no longer in the data set.

**Comment by cameronwaterman** [comment]
After reviewing the API docs a bit more thoroughly, it looks like you can explicitly specify the x axis data type - this fixes the issue. I still question why it doesn't attempt to auto detect on all resets of the data like it does when it is initially set.

**Comment by andrefarzat** [comment]
Hello @cameronwaterman , `angular-plotly.js` is a wrapper for plotly, so it plays with the "default configuration". To make the change you said, what has the inicial data object values and the changed one ?

**Comment by cameronwaterman** [comment]
Initial... notice numeric data on X -axis

    {
        config: {
            displayModeBar: true,
            responsive: true,
            scrollZoom: true
        },
        data: [{
            x: [0, 1, 2],
            y: [2, 3, 4]
        }],
        layout: {
            autosize: true,
            hoverlabel: {
                bgcolor: '#cde4f6'
            },
            hovermode: 'closest',
            legend: {
                orientation: 'h'
            },
            margin: {
                l: 50,
                r: 50,
                b: 50,
                t: 50
            },
            showlegend: true,
            xaxis: {
                type: '-',
                zeroline: false
            },
            yaxis: {
                title: '',
                zeroline: false
            }
        }
    }

Updated... notice datetime on X-axis

    {
        config: {
            displayModeBar: true,
            responsive: true,
            scrollZoom: true
        },
        data: [{
            x: ['2014-12-14 16:34:30.50', '2014-12-15 16:34:30.50', '2014-12-16 16:34:30.50'],
            y: [2, 3, 4]
        }],
        layout: {
            autosize: true,
            hoverlabel: {
                bgcolor: '#cde4f6'
            },
            hovermode: 'closest',
            legend: {
                orientation: 'h'
            },
            margin: {
                l: 50,
                r: 50,
                b: 50,
                t: 50
            },
            showlegend: true,
            xaxis: {
                type: '-',
                zeroline: false
            },
            yaxis: {
                title: '',
                zeroline: false
            }
        }
    }

**Comment by andrefarzat** [comment]
After playing a lot with this issue,  I believe it is related on how `plotly.js` updates itself (once created), and how `angular-plotly.js` asks it to be updated. The change detection happens and everything flows, but I can't figure out why from number to datetime isn't updated. 

Good to know that, if you force the data type on the configuration/layout it works. At least we have a solution for this issue. Thank you 😸
