### ISSUE TITLE
Enable option to turn on showlink

### ISSUE THREAD

**Issue by zyzhu** [plotly/angular-plotly.js#84]
I would like to enable 'Edit in Chart Studio' option by setting `showlink` to be true. But `showlink` is default to false now. 
https://plot.ly/javascript/configuration-options

Is it possible to expose this configuration?

**Comment by andrefarzat** [comment]
Hello @zyzhu, did you tried passing the configuration using the `[config]` property ?
e.g.:
```html
<plotly-plot [config]="{showLink: true}"></plotly-plot>
```

**Comment by zyzhu** [comment]
Thanks! I didn't realize that I can pass `[config]`. Awesome!
