### ISSUE TITLE
(plotly_click) is not being recognized as a function in with plotly-plot selector

### ISSUE THREAD

**Issue by Vatsalyadav** [plotly/angular-plotly.js#85]
Steps to recreate:

template: '<plotly-plot [data]="graph.data" [layout]="graph.layout" (plotly_click)="onDataClick(event)"></plotly-plot>'

Result: No event is being generated when clicked on the chart

**Comment by andrefarzat** [comment]
hello @Vatsalyadav which version of `angular-plotly.js` you're using ?

**Comment by Vatsalyadav** [comment]
> hello @Vatsalyadav which version of `angular-plotly.js` you're using ?

I'm using "angular-plotly.js": "^1.3.2"

**Comment by andrefarzat** [comment]
@Vatsalyadav could not replicate it in current version (`1.4.2`). Reminding that in template the `event` object is `$event`
