### ISSUE TITLE
I am also facing the same issue. I used "angular-plotly.js@1.0.1 and plotly.js@1.44.1". But (selected) not working in Plotly.

### ISSUE THREAD

**Issue by priyavenkat95** [plotly/angular-plotly.js#86]
I am facing the event issue. I used "angular-plotly.js@1.0.1 and plotly.js@1.44.1". But (selected) not working in Plotly.

I used the code below: 
<plotly-plot *ngIf="donut.data" [data]="donut.data" [layout]="donut.layout"    (selected)="handleSelecting($event)"></plotly-plot>

_Originally posted by @priyavenkat95 in https://github.com/plotly/angular-plotly.js/issues/21#issuecomment-542520404_

**Comment by andrefarzat** [comment]
Hello @priyavenkat95 , which plotly.js version you're using ?

**Comment by priyavenkat95** [comment]
Hi andrefarzat, I used plotly.js version is 1.44.1.

**Comment by priyavenkat95** [comment]
Hi André Farzat,


I used the plotly.js version is 1.44.1.


With Regards,

Vishnu Priya B.

________________________________

**Comment by andrefarzat** [comment]
@priyavenkat95  please check this comment: https://github.com/plotly/angular-plotly.js/issues/21#issuecomment-569519251
