### ISSUE TITLE
Chart not displaying

### ISSUE THREAD

**Issue by santosdanilo** [plotly/angular-plotly.js#87]
When trying to plot a chart, the error show this message.
Error while plotting: TypeError: Cannot set property '__data__' of undefined
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'data' of undefined
TypeError: Cannot read property 'data' of undefined
    at PlotComponent.push../src/app/shared/plot/plot.component.ts.PlotComponent.createFigure

First i thought it was something, on my app. But this is happening with the demo app too.
It's look like is some problem on createPlot, not saving plolyInstance, and when it's required on createFigure, cound't find plotlyInstance.data of undefined.

![Screenshot from 2019-11-17 19-00-29](https://user-images.githubusercontent.com/10814731/69014789-b8d05380-096c-11ea-8ab2-8d6d7a3e0b10.png)

**Comment by andrefarzat** [comment]
@santosdanilo running the demo is working for me here. I need more info to replicate your issue.
What versions of `angular-plotly.js` and `plotly.js` you're using ?

**Comment by santosdanilo** [comment]
I was using the same on the package.json

**Comment by santosdanilo** [comment]
@andrefarzat This error just doesn't show anymore. It was ocurring on my coworkers computer too, but after some days, it stopped to happen. Maybe it was some problem on the browser.
