### ISSUE TITLE
Angular plotly is slow with large datasets

### ISSUE THREAD

**Issue by loth0** [plotly/angular-plotly.js#90]
This fiddle in pure plotly js runs really smoothly, especially when rendering with webgl:

https://jsfiddle.net/kb8us6Lo/

When creating the same graphs in angular plotly hovering and zooming becomes really laggy.

HTML:

         <plotly-plot [data]="data" [layout]="layout"> </plotly-plot>
         <plotly-plot [data]="data" [layout]="layout"> </plotly-plot>

Code for component:

      export class AppComponent implements OnInit {
         data: any;
         layout: any;

      ngOnInit(): void {
        this.layout = { showlegend: false };
        this.data = this.getData();
      }

      getData() {
        const startValue = 0;
        const stopValue = 100000;
        const pointNum = 10000;
        const traceNum = 10;
        const currValue = startValue;
        const step = (stopValue - startValue) / (pointNum - 1);

        const data = [];

        for (let j = 0; j < traceNum; j++) {
          const X = [];
          const Y = [];
          for (let i = 0; i < pointNum; i++) {
            X.push(currValue + step * i);
            Y.push(this.gaussianRand() * 8 + j * 5);
          }
          data.push({
            type: 'scattergl',
            mode: 'line',
            x: X,
            y: Y
          });
        }

        return data;
      }

      gaussianRand() {
        let rand = 0;
        for (let i = 0; i < 6; i += 1) {
          rand += Math.random();
        }
        return rand / 6 - 0.5;
      }
    }

**Comment by andrefarzat** [comment]
I could see the slowlyness you're saying. This might due the angular checking mechanism ... I will test disabling it ( e.g.: forcing it NOT being checked ) and see if the performance improves

**Comment by andrefarzat** [comment]
Just added the `updateOnlyWithRevision` property. When setting this to `true`, the component will skip the `ngDoCheck` which is the reason why the interaction with the graph becomes slow

**Comment by jamilraichouni** [comment]
Perfect! Thank you! Dealing with a dozen and more family of curves with 300,000 points in one graph. Thanks to the above it works like a charm 😃

**Comment by eawachtel** [comment]
I'm trying to use the 'updateOnlyWithRevision and I'm getting errors saying 'Can't bind to 'updateOnlyWithRevision' since it isn't a known property of 'plotly-plot'.'

I'm currently on angular 8, angular-plotly-js 1.4.2, plotly.js 1.50.1

**Comment by andrefarzat** [comment]
@eawachtel I believe the `updateOnlyWithRevision` property was added after version `1.5.0` of `angular-plotly.js`. Would you mind updating to most recent version? (e.g.: `1.8.0` at the time of this comment)
