### ISSUE TITLE
TypeError: this is undefined plotly.js

### ISSUE THREAD

**Issue by steeveone** [plotly/angular-plotly.js#91]
following the guide I get in browser console:

>TypeError: this is undefinedplotly.js:24874
    ./node_modules/plotly.js/dist/plotly.js/</<[164]</< plotly.js:24874
    ./node_modules/plotly.js/dist/plotly.js/</<[164]< plotly.js:34420
    o plotly.js:7
    o plotly.js:7
    ./node_modules/plotly.js/dist/plotly.js/</<[716]< plotly.js:105364
    o plotly.js:7
    o plotly.js:7
    ./node_modules/plotly.js/dist/plotly.js/</<[1]< plotly.js:10
    o plotly.js:7
    o plotly.js:7
    ./node_modules/plotly.js/dist/plotly.js/</<[694]< plotly.js:102433
    o plotly.js:7
    o plotly.js:7
    ./node_modules/plotly.js/dist/plotly.js/</<[14]< plotly.js:242
    o plotly.js:7
    o plotly.js:7
    ./node_modules/plotly.js/dist/plotly.js/</<[26]< plotly.js:398
    o plotly.js:7
    r plotly.js:7
    js plotly.js:7
    js plotly.js:7
    js plotly.js:7
    Webpack 12

**Comment by andrefarzat** [comment]
Using angular 8? 
Probably the issue is related to the es5 module: https://github.com/plotly/angular-plotly.js/issues/76#issuecomment-526872398

Please, let me know if this solves

**Comment by steeveone** [comment]
Yes it solves,
many thanks!
