### ISSUE TITLE
Creating buttons and modebarButtons

### ISSUE THREAD

**Issue by mikezero84** [plotly/angular-plotly.js#93]
According with the plotly javascript documentation I can create new menu buttons and modebarButtons adding to the layout property "updatemenus" and/or "modeBarButtons" but, how these features works in your component? (angular-plotly), I've been trying to create an updatemenu and an modebarButtons like this:

`Plotly.d3.csv('https://raw.githubusercontent.com/plotly/datasets/master/api_docs/mt_bruno_elevation.csv', function(err, rows){
function unpack(rows, key) {
  return rows.map(function(row) { return row[key]; });
}
var z_data=[ ]
for(i=0;i<24;i++)
{
  z_data.push(unpack(rows,i));
}

var data = [{
        z: z_data, 
        type:'surface',
        colorscale:'Viridis'
}]

var updatemenus=[
    {
        buttons: [   
            {
                args: ['type', 'surface'],
                label: '3D Surface',
                method: 'restyle'
            },
            {
                args: ['type', 'heatmap'],
                label:'Heatmap',
                method:'restyle'
            }             
        ],
        direction: 'left',
        pad: {'r': 10, 't': 10},
        showactive: true,
        type: 'buttons',
        x: 0.15,
        xanchor: 'left',
        y: 1.1,
        yanchor: 'top' 
    }
]

var annotations = [
    {
      text: 'Trace type:', 
      x: 0, 
      y: 1.06, 
      yref: 'paper', 
      align: 'left', 
      showarrow: false
    }
]

var layout = {
    margin: {t: 0, b: 0, l: 0, r: 0},
    updatemenus: updatemenus,
    annotations: annotations,
    scene: {
        xaxis:{
            gridcolor: 'rgb(255, 255, 255)',
            zerolinecolor: 'rgb(255, 255, 255)',
            showbackground: true,
            backgroundcolor:'rgb(230, 230,230)'
        },
        yaxis: {
            gridcolor: 'rgb(255, 255, 255)',
            zerolinecolor: 'rgb(255, 255, 255)',
            showbackground: true,
            backgroundcolor: 'rgb(230, 230, 230)'
        },
        zaxis: {
            gridcolor: 'rgb(255, 255, 255)',
            zerolinecolor: 'rgb(255, 255, 255)',
            showbackground: true,
            backgroundcolor: 'rgb(230, 230,230)'
        },
        aspectratio: {x: 1, y: 1, z: 0.7},
        aspectmode: 'manual'
  }
}

Plotly.plot("myDiv", data, layout, {showSendToCloud: true});
});`

modebarButtons
`let data = {
  x: [0, 1, 2, 3, 4],
  y: [-1, 5, 2, 3, 3]
}

let layout = {
  xaxis: {
    range: [-1, 5]
  }
}

let lockIcon = {
  'width': 1000,
  'height': 1000,
  'path': "M320 768h512v192q0 106 -75 181t-181 75t-181 -75t-75 -181v-192zM1152 672v-576q0 -40 -28 -68t-68 -28h-960q-40 0 -68 28t-28 68v576q0 40 28 68t68 28h32v192q0 184 132 316t316 132t316 -132t132 -316v-192h32q40 0 68 -28t28 -68z",
  'transform': 'matrix(0.75 0 0 -0.75 0 1000)'
}

let modeBarButtons = [[
  {
    name: 'Custom Lock',
    icon: lockIcon,
    click: () => { alert('clicked custom button!'); }
  },
  { 
    name: 'Snapshot',
    icon: Plotly.Icons.camera,
    click: () => { alert('new button!'); }
  }, "zoom2d", "pan2d" ]];

Plotly.react('plot', [data], layout, { modeBarButtons: modeBarButtons });`

This feature it's able in your component, because i didn't see any example, thanks for your time.

**Comment by andrefarzat** [comment]
Regarding [plotly's documentation](https://plot.ly/javascript/plotlyjs-function-reference/#plotlynewplot), `Plotly.react`'s third argument is the `config`. Therefore, you could pass the object `modeBarButtons` via property:

```ts
import { Component } from '@angular/core';

@Component({
    selector: 'plotly-example',
    template: '<plotly-plot [data]="graph.data" [layout]="graph.layout" [config]="graph.config></plotly-plot>',
})
export class PlotlyExampleComponent {
    public graph = {
        data: [
            { x: [1, 2, 3], y: [2, 6, 3], type: 'scatter', mode: 'lines+points', marker: {color: 'red'} },
            { x: [1, 2, 3], y: [2, 5, 3], type: 'bar' },
        ],
        layout: {
            width: 320,
            height: 240,
            title: 'A Fancy Plot'
        },
        config: {
            modeBarButtons: [
                [{
                        name: 'Custom Lock',
                        icon: lockIcon,
                        click: () => {
                            alert('clicked custom button!');
                        }
                    },
                    {
                        name: 'Snapshot',
                        icon: Plotly.Icons.camera,
                        click: () => {
                            alert('new button!');
                        }
                    }, "zoom2d", "pan2d"
                ]
            ]
        }
    };
}
```

**Comment by mikezero84** [comment]
Cool!!!

I going to test it, and this config also works for "updatemenus" to create custom buttons?, like this case:
https://plot.ly/javascript/custom-buttons/

**Comment by andrefarzat** [comment]
@mikezero84 definitely!  The "frames" example on the demo uses it. Check it out: https://github.com/plotly/angular-plotly.js/tree/master/src/app/demo/frames

**Comment by Alqua** [comment]
Did any of you succeed to create a lock button? I would very much enjoy a lock button to keep the zoom function available but keep it from triggering when it's not needed.
I think my knowledge is not strong enough to create it myself ;(

**Comment by andrefarzat** [comment]
@Alqua I am not sure if plotly.js itself is able of doing that. You can zoom in/out but I don't think there is a "lock" in an specific zoom-level

**Comment by Alqua** [comment]
@andrefarzat I meant lock the whole modebar or even remove the autoselect of the zoom function. I've seen you are using the lock Icon, I thought is what you wanted to do.

I have a ggplotly object published online. My problem is that when looking at it on a phone, scrolling down while on the charts actually triggers a "zoom select", which is the first option autoselected on the modebar.

I removed the zoom function where it is not needed but it is still useful for some graph. I dont know how to get around that.
