### ISSUE TITLE
Feature request: changelog

### ISSUE THREAD

**Issue by koesper** [plotly/angular-plotly.js#95]
Are there any resources to figure out what the changes in a release are?
There is are no releasenotes or a  CHANGELOG.md.  And since the versioning and release of angular-plotly.js is independent to plotly.js or react-plotly.js, it is quite hard to figure out where the changes are.

**Comment by koesper** [comment]
I know doing a [code comparison between tags](https://github.com/plotly/angular-plotly.js/compare/v1.4.2...v1.5.0) works, but that only shows the result, not the reason.

**Comment by andrefarzat** [comment]
@koesper just added the "changelog.md" file as you asked. I don't have the time to update backwards, but I will make an effort to keep it updated from now on 😺
