### ISSUE TITLE
plotly doesn't display first two charts in loop

### ISSUE THREAD

**Issue by lchaudharyPinchin** [plotly/angular-plotly.js#96]
Here is my code.
`<div *ngIf="yChartData.length > 0; else noData;">
                            <span *ngFor="let chart of yChartData">
                                <plotly-plot 
                                    [data]="chart.data"
                                    [layout]="chart.layout"
                                    [config]="chart.config"
                                    [useResizeHandler]="true"
                                    [className]="chart-area"
                                    [style]="chart.style"
                                    (plotly_click)="onDataClick($event)"
                                    >
                                </plotly-plot>
                            </span>
                        </div>
                        <ng-template #noData>No Data avaialbe for this station</ng-template>`

Issue:- If we have 6 charts, but while rendering display only 4, this will skip the top 2 charts from the list.

Environment:- 
Angular: 8.2.14
angular-plotly.js: 1.5.0

**Comment by lchaudharyPinchin** [comment]
I found the solution, had to remove the config property responsive from config. Now its working and display all charts

**Comment by zenymax** [comment]
Thanks, I got that issue too. when remove the responsive from config, it works have no idea why is that
