### ISSUE TITLE
Performance with initializing multiple plot components at once

### ISSUE THREAD

**Issue by dsa821** [plotly/angular-plotly.js#97]
Hello,

I am trying to display multiple bar charts on the same page at the same time (at least 50, potentially up to 100 or so). I've noticed that the initialization time of an individual plot seems to be affected by how many total plots there are.

For example, 1 chart might take around 30 ms (based on when the `(initialized)` callback fires). 10 charts starts causing them to take around 250 ms. 50 charts is closer to 1500 ms. Obviously having more charts will be slower overall, but I wasn't expecting all individual `(initialized)` callbacks to take longer, and then fire all at once.

[Stackblitz here](https://stackblitz.com/edit/angular-plotly-performance) - initialization times are being logged to the console.

**Comment by dsa821** [comment]
On further investigation, it seems like this behavior occurs when using the base plotly.js library without the angular-plotly wrapper.

**Comment by leeoniya** [comment]
also https://bugs.chromium.org/p/chromium/issues/detail?id=771792

**Comment by dsa821** [comment]
I'd actually like to reopen this to see if something can be done on the angular-plotly side. By calling `Plotly.newPlot` inside a `setTimeout` function, it at least allows the UI to start rendering plots individually, instead of being blocked until they all initialize.

I've updated the previous [Stackblitz](https://stackblitz.com/edit/angular-plotly-performance) to demonstrate.

**Comment by andrefarzat** [comment]
hello @dsa821 I started experimenting with your code directly in the `angular-plotly.js` code. Please check the [performance branch](https://github.com/plotly/angular-plotly.js/tree/performance). I am replicating your experiment, but no luck so far. Check this print:

<img width="1750" alt="Screen Shot 2020-02-22 at 14 46 47" src="https://user-images.githubusercontent.com/649219/75096849-74afa900-5582-11ea-8c59-bf32cc8de8ea.png">

Even though I added the [setTimeout](https://github.com/plotly/angular-plotly.js/blob/performance/src/app/shared/plot/plot.component.ts#L106), I could not see the same performance gain you've in your example. 

May I ask your help in this task? 😸

**Comment by dsa821** [comment]
Hi @andrefarzat, I think what you're seeing is just a difference in how we are measuring the start times in the experiment. If you move the `ngInited` event inside the `setTimeout`:

```ts
setTimeout(async () => {
    this.ngInited.emit();
    await this.createPlot();
    const figure = this.createFigure();
    this.initialized.emit(figure);
});
```

Then you'll see similar results.

![image](https://user-images.githubusercontent.com/6894511/75475121-15201780-594d-11ea-81b3-0beaac13e54d.png)

You can also compare without the setTimeout:
```ts
this.ngInited.emit();
this.createPlot().then(() => {
    const figure = this.createFigure();
    this.initialized.emit(figure);
});
```

Note that this trick doesn't actually improve the overall page load time, it just allows individual plots to start rendering on the page faster. Total time that you are measuring still stays about the same.

If you start on the demo home page and try navigating to the performance page with and without the setTimeout, you'll see a noticeable difference in how fast the performance page comes up.
