### ISSUE TITLE
Setting Chart Themes 

### ISSUE THREAD

**Issue by laredoza** [plotly/angular-plotly.js#99]
Hi,

My apologies if this isn't the right place to ask but how would I go about setting the theme? i.e) 
fig.layout.template = 'plotly_dark' .

I've tried setting up my layout config as follows:

```
,
    layout: {
      template: "plotly_dark",
      dragmode: "zoom",
      ......
```

Regards

**Comment by andrefarzat** [comment]
Hello @laredoza, looks like theming/templates are a feature of plotly.py only. I will see if we can bring these themes to angular-plotly.js also 😺

**Comment by laredoza** [comment]
Thanks, appreciate it
